(function(){"use strict";
  var state={config:null,zones:[],results:[],streams:[],timers:[],historyMinutes:1440};
  function id(v){return document.getElementById(v)}function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function text(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}function num(v){if(v===null||v===undefined||v==="")return null;var n=Number(v);return Number.isFinite(n)?n:null}function on(v){return /^(1|true|on|open|alarm)$/i.test(String(v==null?"":v).trim())}
  function hydrate(raw){var c=window.ROSA_SIMULATOR_CONTEXT||{};return String(raw||"").replace(/<<sessionid>>/gi,text(c.sessionId,"IO123abcd@simulate")).replace(/<<syncid>>/gi,text(c.syncId,"SIM_SYNC"))}
  function parse(){try{return JSON.parse(hydrate(id("cold-storage-config").textContent))}catch(e){return null}}
  function zone(raw,index){raw=raw||{};var f=raw.fields||{},t=raw.thresholds||{};return{name:text(raw.name,"Kho "+(index+1)),description:text(raw.description,""),sessionId:text(raw.sessionId,""),accent:text(raw.accent,["#0ea5e9","#14b8a6","#22c55e"][index%3]),thresholds:{tempMin:Number(t.tempMin),tempMax:Number(t.tempMax),humidityMax:Number(t.humidityMax)},fields:{temperature:text(f.temperature,""),humidity:text(f.humidity,""),door:text(f.door,""),compressor:text(f.compressor,""),powerStatus:text(f.powerStatus,""),powerW:text(f.powerW,""),alarm:text(f.alarm,"")}}}
  function empty(z){return{zone:z,payload:{},rows:[],lastSeen:0,connection:"connecting"}}
  function fields(z){return Object.keys(z.fields).map(function(k){return z.fields[k]}).filter(Boolean)}function seriesFields(z){return[z.fields.temperature,z.fields.humidity,z.fields.powerW].filter(Boolean)}
  function queryUrl(z,type){if(!z.sessionId||!state.config.syncId)return"";var q=new URLSearchParams(),now=Date.now();q.set("fields",(type==="iotimeseries"?seriesFields(z):fields(z)).join(","));if(type==="iotimeseries"){q.set("from",String(now-state.historyMinutes*60000));q.set("to",String(now))}return"/api/"+encodeURIComponent(z.sessionId)+"/"+encodeURIComponent(state.config.syncId)+"/"+type+"?"+q}
  function streamUrl(z){var q=new URLSearchParams();q.set("fields",fields(z).join(","));return"/api/"+encodeURIComponent(z.sessionId)+"/stream?"+q}
  function read(result,field){var target=String(field||"").toLowerCase(),found=null;Object.keys(result.payload||{}).some(function(k){if(k.toLowerCase()===target){found=result.payload[k];return true}return false});return found}
  function fetchJson(url){if(!url)return Promise.resolve(null);return fetch(url,{cache:"no-store"}).then(function(r){return r.ok?r.json():null}).catch(function(){return null})}
  function bootstrap(index){var z=state.zones[index];return Promise.all([fetchJson(queryUrl(z,"iotelemetry")),fetchJson(queryUrl(z,"iotimeseries"))]).then(function(parts){var r=state.results[index],tele=parts[0]&&parts[0].c2,ts=parts[1]&&parts[1].c2;r.payload=Object.assign({},r.payload,tele&&tele.payload||{});r.lastSeen=Number(tele&&tele.serverTime)||r.lastSeen;r.rows=(ts&&Array.isArray(ts.rows)?ts.rows:[]).filter(function(row){return String(row.field||"").toLowerCase()===z.fields.temperature.toLowerCase()}).map(function(row){return{ts:Number(row.ts),value:Number(row.value)}}).filter(function(p){return Number.isFinite(p.ts)&&Number.isFinite(p.value)});render()}).catch(function(){})}
  function appendRows(index,rows){var r=state.results[index],field=state.zones[index].fields.temperature.toLowerCase();(rows||[]).forEach(function(row){if(String(row.field||"").toLowerCase()!==field)return;var p={ts:Number(row.ts),value:Number(row.value)};if(Number.isFinite(p.ts)&&Number.isFinite(p.value))r.rows.push(p)});var cutoff=Date.now()-state.historyMinutes*60000;r.rows=r.rows.filter(function(p){return p.ts>=cutoff}).slice(-240)}
  function connect(index){var z=state.zones[index],r=state.results[index],source;try{source=new EventSource(streamUrl(z));state.streams[index]=source;source.onopen=function(){r.connection="online";render()};source.onmessage=function(event){try{var data=JSON.parse(event.data);r.connection="online";if(data.type==="telemetry"&&data.payload){r.payload=Object.assign({},r.payload,data.payload);r.lastSeen=Number(data.serverTime)||Date.now()}else if(data.type==="timeseries")appendRows(index,data.rows);render()}catch(e){}};source.onerror=function(){source.close();state.streams[index]=null;r.connection="offline";render();clearTimeout(state.timers[index]);state.timers[index]=setTimeout(function(){connect(index)},3000)}}catch(e){r.connection="offline";render()}}
  function assessment(result){var z=result.zone,temp=num(read(result,z.fields.temperature)),humidity=num(read(result,z.fields.humidity)),doorRaw=read(result,z.fields.door),compressorRaw=read(result,z.fields.compressor),powerRaw=read(result,z.fields.powerStatus),powerW=num(read(result,z.fields.powerW)),alarmRaw=read(result,z.fields.alarm),doorOpen=doorRaw==null?false:(state.config.doorOpenIsOn?on(doorRaw):!on(doorRaw)),power=powerRaw==null?false:on(powerRaw),issues=[],hasData=temp!==null||humidity!==null||doorRaw!=null||compressorRaw!=null||powerRaw!=null||powerW!==null||alarmRaw!=null;if(result.connection==="offline")issues.push("Mất kết nối");if(temp!==null&&(temp<z.thresholds.tempMin||temp>z.thresholds.tempMax))issues.push("Nhiệt độ vượt ngưỡng");if(humidity!==null&&Number.isFinite(z.thresholds.humidityMax)&&humidity>z.thresholds.humidityMax)issues.push("Độ ẩm cao");if(doorRaw!=null&&doorOpen)issues.push("Cửa đang mở");if(powerRaw!=null&&!power)issues.push("Mất nguồn");if(alarmRaw!=null&&on(alarmRaw))issues.push("Thiết bị báo lỗi");return{temp:temp,humidity:humidity,doorOpen:doorOpen,compressor:compressorRaw==null?false:on(compressorRaw),power:power,powerW:powerW,alarm:issues.length>0,issues:issues,hasData:hasData}}
  function path(points){if(!points.length)return{line:"",area:""};var vals=points.map(function(p){return p.value}),min=Math.min.apply(null,vals),max=Math.max.apply(null,vals);if(max-min<2){min-=1;max+=1}var line=points.map(function(p,i){var x=8+i*(144/Math.max(1,points.length-1)),y=82-(p.value-min)/(max-min)*62;return(i?"L":"M")+x.toFixed(1)+" "+y.toFixed(1)}).join(" ");return{line:line,area:line+" L152 84 L8 84 Z"}}
  function timeAgo(ts){if(!ts)return"Chưa có dữ liệu";var sec=Math.max(0,Math.round((Date.now()-ts)/1000));if(sec<60)return sec+" giây trước";if(sec<3600)return Math.round(sec/60)+" phút trước";return Math.round(sec/3600)+" giờ trước"}
  function zoneHtml(result,index){var z=result.zone,a=assessment(result),p=path(result.rows),stateName=a.alarm?"danger":"normal";return'<article class="cs-zone" data-alarm="'+a.alarm+'" style="--accent:'+esc(z.accent)+'"><div class="cs-zone-head"><div class="cs-zone-title"><i class="cs-dot" data-state="'+stateName+'"></i><div><h2>'+esc(z.name)+'</h2><p>'+esc(z.description)+'</p></div></div><div class="cs-zone-state" data-state="'+stateName+'">'+(a.alarm?'CẦN KIỂM TRA':'ỔN ĐỊNH')+'</div></div><div class="cs-temp-row"><div><div class="cs-temp-value" data-state="'+(a.temp!==null&&(a.temp<z.thresholds.tempMin||a.temp>z.thresholds.tempMax)?'danger':'normal')+'">'+(a.temp===null?'--':a.temp.toFixed(1))+'°C</div><div class="cs-threshold">Ngưỡng '+z.thresholds.tempMin+'°C đến '+z.thresholds.tempMax+'°C</div></div><svg class="cs-chart" viewBox="0 0 160 92" preserveAspectRatio="none"><line class="cs-chart-grid" x1="8" y1="22" x2="152" y2="22"/><line class="cs-chart-grid" x1="8" y1="52" x2="152" y2="52"/><line class="cs-chart-grid" x1="8" y1="82" x2="152" y2="82"/><path class="cs-chart-area" d="'+p.area+'"/><path class="cs-chart-line" d="'+p.line+'"/></svg></div><div class="cs-metrics"><div class="cs-metric"><span>Độ ẩm</span><strong data-state="'+(a.humidity!==null&&a.humidity>z.thresholds.humidityMax?'danger':'normal')+'">'+(a.humidity===null?'--':a.humidity.toFixed(0)+'%')+'</strong></div><div class="cs-metric"><span>Cửa kho</span><strong data-state="'+(a.doorOpen?'danger':'normal')+'">'+(a.doorOpen?'ĐANG MỞ':'Đã đóng')+'</strong></div><div class="cs-metric"><span>Máy nén</span><strong>'+(a.compressor?'Đang chạy':'Đang nghỉ')+'</strong></div><div class="cs-metric"><span>Nguồn điện</span><strong data-state="'+(a.power?'normal':'danger')+'">'+(a.power?'Bình thường':'Mất nguồn')+'</strong></div><div class="cs-metric"><span>Công suất</span><strong>'+(a.powerW===null?'--':a.powerW.toFixed(0)+' W')+'</strong></div><div class="cs-metric"><span>Cảnh báo</span><strong data-state="'+(a.alarm?'danger':'normal')+'">'+(a.issues.length?esc(a.issues[0]):'Không có')+'</strong></div></div><div class="cs-zone-foot"><span>'+esc(result.connection==="online"?'Trực tuyến':'Ngoại tuyến')+'</span><span>Cập nhật '+timeAgo(result.lastSeen)+'</span></div></article>'}
  function render(){if(!state.config)return;var checks=state.results.map(assessment),online=state.results.filter(function(r){return r.connection==="online"}).length,alarms=checks.filter(function(a){return a.alarm}).length,temps=checks.map(function(a){return a.temp}).filter(function(v){return v!==null}),avg=temps.length?temps.reduce(function(s,v){return s+v},0)/temps.length:null,power=checks.reduce(function(s,a){return s+(a.powerW||0)},0);id("cs-kpis").innerHTML=[["Kho trực tuyến",online+"/"+state.zones.length,"Kết nối realtime"],["Kho cảnh báo",alarms+" kho",alarms?"Cần kiểm tra ngay":"Tất cả ổn định"],["Nhiệt độ trung bình",avg===null?"--":avg.toFixed(1)+"°C","Trên toàn hệ thống"],["Tổng công suất",power.toFixed(0)+" W","Tải tức thời"]].map(function(k){return'<article class="cs-kpi"><span>'+k[0]+'</span><strong>'+k[1]+'</strong><small>'+k[2]+'</small></article>'}).join("");id("cs-zone-grid").innerHTML=state.results.length?state.results.map(zoneHtml).join(""):'<div class="cs-empty">Chưa có kho nào được cấu hình.</div>';var messages=[];state.results.forEach(function(r,i){var a=checks[i];if(a.alarm)messages.push(r.zone.name+": "+a.issues.join(", "))});var alert=id("cs-alert");alert.hidden=!messages.length;alert.textContent=messages.length?"⚠ "+messages.join("  •  "):"";var live=id("cs-live-dot"),label=id("cs-live-text");live.setAttribute("data-state",online?"online":"offline");label.textContent=online?online+" kho trực tuyến":"Mất kết nối"}
  function clarifyMissingData(){var cards=id("cs-zone-grid").querySelectorAll(".cs-zone");state.results.forEach(function(result,index){var a=assessment(result),card=cards[index];if(a.hasData||!card)return;var badge=card.querySelector(".cs-zone-state"),dot=card.querySelector(".cs-dot");if(badge&&badge.textContent!=="CHƯA CÓ DỮ LIỆU"){badge.textContent="CHƯA CÓ DỮ LIỆU";badge.style.color="#b45309";badge.style.background="rgba(245,158,11,.12)"}if(dot)dot.style.background="#f59e0b";card.querySelectorAll(".cs-metric strong").forEach(function(node){if(node.textContent!=="--")node.textContent="--";node.removeAttribute("data-state")})});var hasData=state.results.some(function(r){return assessment(r).hasData}),note=id("cs-kpis").children[1]&&id("cs-kpis").children[1].querySelector("small");if(note&&!hasData&&note.textContent!=="Đang chờ dữ liệu")note.textContent="Đang chờ dữ liệu";if(!hasData&&state.results.some(function(r){return r.connection==="connecting"})){id("cs-live-dot").setAttribute("data-state","connecting");id("cs-live-text").textContent="Đang kết nối"}}
  function reloadHistory(){state.results.forEach(function(r){r.rows=[]});Promise.all(state.zones.map(function(z,i){return fetchJson(queryUrl(z,"iotimeseries")).then(function(payload){var rows=payload&&payload.c2&&payload.c2.rows||[];appendRows(i,rows)}).catch(function(){})})).then(render)}
  function theme(){var p=id("theme-picker"),t=id("theme-picker-toggle"),m=id("theme-picker-menu");function open(value){p.classList.toggle("is-open",value);t.setAttribute("aria-expanded",value?"true":"false")}t.setAttribute("aria-label","Chọn màu giao diện");t.setAttribute("aria-haspopup","true");open(false);t.onclick=function(e){e.stopPropagation();open(!p.classList.contains("is-open"))};m.onclick=function(e){var b=e.target.closest("[data-theme-option]");if(!b)return;var v=b.getAttribute("data-theme-option");document.documentElement.setAttribute("data-theme",v);try{localStorage.setItem("sample-dashboard-theme",v)}catch(x){}m.querySelectorAll("button").forEach(function(n){n.classList.toggle("is-active",n===b)});open(false)};document.addEventListener("click",function(e){if(!p.contains(e.target))open(false)})}
  function init(){var c=parse();if(!c)return;state.config={syncId:text(c.syncId,""),doorOpenIsOn:c.doorOpenIsOn!==false};state.historyMinutes=Number(c.historyMinutes)||1440;state.zones=(Array.isArray(c.zones)?c.zones:[]).map(zone);state.results=state.zones.map(empty);id("cs-title").textContent=text(c.title,"Giám sát kho lạnh");id("cs-subtitle").textContent=text(c.subtitle,"");id("cs-range").value=String(state.historyMinutes);id("cs-range").onchange=function(){state.historyMinutes=Number(this.value)||1440;reloadHistory()};function updateClock(){id("cs-clock").textContent=new Date().toLocaleTimeString("vi-VN")}updateClock();setInterval(updateClock,1000);theme();if(window.MutationObserver)new MutationObserver(clarifyMissingData).observe(id("cs-zone-grid"),{childList:true,subtree:true});render();clarifyMissingData();state.zones.forEach(function(z,i){bootstrap(i).finally(function(){connect(i)})})}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
