(function(){"use strict";
  function makeZone(index,name,prefix,min,max,humidity,accent){return{name:name,description:"Khu lưu trữ "+(index+1),sessionId:"<<sessionid>>",accent:accent,thresholds:{tempMin:min,tempMax:max,humidityMax:humidity},fields:{temperature:prefix+"_temperature",humidity:prefix+"_humidity",door:prefix+"_door",compressor:prefix+"_compressor",powerStatus:prefix+"_power",powerW:prefix+"_power_w",alarm:prefix+"_alarm"}}}
  var DEFAULT={locale:"vi",title:"Giám sát kho lạnh",subtitle:"Theo dõi nhiệt độ, cửa kho, máy nén và nguồn điện 24/7",syncId:"<<syncid>>",historyMinutes:1440,doorOpenIsOn:true,zones:[makeZone(0,"Kho đông","freezer",-25,-15,90,"#0ea5e9"),makeZone(1,"Kho mát","cooler",2,8,85,"#14b8a6"),makeZone(2,"Kho rau củ","produce",8,14,95,"#22c55e")]};
  var state={config:clone(DEFAULT),context:{}};function clone(v){return JSON.parse(JSON.stringify(v==null?{}:v))}function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function safe(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}function num(v,f){var n=Number(v);return Number.isFinite(n)?n:Number(f||0)}
  function general(label,key,value,type){return'<label>'+esc(label)+'<input data-general="'+key+'" type="'+(type||"text")+'" value="'+esc(value)+'"></label>'}function zinput(label,key,value,type){return'<label>'+esc(label)+'<input data-zone-key="'+key+'" type="'+(type||"text")+'" value="'+esc(value)+'"></label>'}function threshold(label,key,value){return'<label>'+esc(label)+'<input data-threshold="'+key+'" type="number" step="0.1" value="'+esc(value)+'"></label>'}function field(label,key,value){return'<label>'+esc(label)+'<input data-field="'+key+'" value="'+esc(value)+'"></label>'}
  function zoneHtml(z,index){var t=z.thresholds||{},f=z.fields||{};return'<article class="item-card" data-zone="'+index+'"><div class="item-top"><div><span class="badge">#'+(index+1)+'</span> <strong>'+esc(z.name)+'</strong></div><div><button class="secondary" data-action="clone" data-index="'+index+'">Nhân bản</button> <button class="danger" data-action="delete" data-index="'+index+'">Xóa</button></div></div><div class="grid">'+zinput("Tên kho","name",z.name)+zinput("Mô tả","description",z.description)+zinput("Device key","sessionId",z.sessionId)+zinput("Màu nhận diện","accent",z.accent,"color")+threshold("Nhiệt độ thấp nhất (°C)","tempMin",t.tempMin)+threshold("Nhiệt độ cao nhất (°C)","tempMax",t.tempMax)+threshold("Độ ẩm tối đa (%)","humidityMax",t.humidityMax)+'</div><div class="advanced"><h3>Field thiết bị</h3><div class="grid">'+field("Nhiệt độ","temperature",f.temperature)+field("Độ ẩm","humidity",f.humidity)+field("Cửa kho","door",f.door)+field("Máy nén","compressor",f.compressor)+field("Nguồn điện","powerStatus",f.powerStatus)+field("Công suất W","powerW",f.powerW)+field("Cảnh báo ON/OFF","alarm",f.alarm)+'</div></div></article>'}
  function render(){var c=state.config,zones=Array.isArray(c.zones)?c.zones:[];document.body.innerHTML='<main class="shell"><header class="head"><div><h1>Cài đặt giám sát kho lạnh</h1><div class="status">Cấu hình ngưỡng cảnh báo và field cho từng kho.</div></div><div class="badge">'+zones.length+' kho</div></header><section class="panel"><h2>Thông tin chung</h2><div class="grid">'+general("Tên dashboard","title",c.title)+general("AccountID dùng chung","syncId",c.syncId)+general("Lịch sử mặc định (phút)","historyMinutes",c.historyMinutes,"number")+'<label class="full">Mô tả<input data-general="subtitle" value="'+esc(c.subtitle)+'"></label><label>Quy ước cửa<select data-general="doorOpenIsOn"><option value="true"'+(c.doorOpenIsOn!==false?' selected':'')+'>ON = cửa mở</option><option value="false"'+(c.doorOpenIsOn===false?' selected':'')+'>OFF = cửa mở</option></select></label></div></section><section class="panel"><div class="toolbar"><h2>Danh sách kho</h2><button data-action="add">+ Thêm kho</button></div><div class="item-list">'+zones.map(zoneHtml).join("")+'</div></section></main>';DashboardSetupBridge.resize()}
  function read(){var c=state.config;document.querySelectorAll("[data-general]").forEach(function(n){var k=n.getAttribute("data-general");if(k==="historyMinutes")c[k]=Math.max(15,num(n.value,1440));else if(k==="doorOpenIsOn")c[k]=n.value==="true";else c[k]=safe(n.value,c[k])});document.querySelectorAll("[data-zone]").forEach(function(card){var z=c.zones[Number(card.getAttribute("data-zone"))];card.querySelectorAll("[data-zone-key]").forEach(function(n){z[n.getAttribute("data-zone-key")]=safe(n.value,z[n.getAttribute("data-zone-key")])});z.thresholds=z.thresholds||{};card.querySelectorAll("[data-threshold]").forEach(function(n){z.thresholds[n.getAttribute("data-threshold")]=num(n.value,z.thresholds[n.getAttribute("data-threshold")])});z.fields=z.fields||{};card.querySelectorAll("[data-field]").forEach(function(n){z.fields[n.getAttribute("data-field")]=safe(n.value,"")})})}
  function initialize(payload){state.context=clone(payload&&payload.context||{});var c=payload&&payload.config;state.config=clone(c&&Object.keys(c).length?c:DEFAULT);if(!state.config.syncId)state.config.syncId=state.context.syncId||"";(state.config.zones||[]).forEach(function(z){if(!z.sessionId)z.sessionId=state.context.sessionId||""});render()}function collect(){read();if(!state.config.title)throw new Error("Hãy nhập tên dashboard.");if(!state.config.zones.length)throw new Error("Cần ít nhất một kho.");state.config.zones.forEach(function(z){if(z.thresholds.tempMin>=z.thresholds.tempMax)throw new Error(z.name+": ngưỡng thấp phải nhỏ hơn ngưỡng cao.")});return clone(state.config)}
  document.addEventListener("click",function(e){var b=e.target.closest("[data-action]");if(!b)return;e.preventDefault();read();var a=b.getAttribute("data-action"),i=Number(b.getAttribute("data-index"));if(a==="add"){var n=state.config.zones.length+1;state.config.zones.push(makeZone(n-1,"Kho "+n,"zone"+n,2,8,90,"#8b5cf6"))}else if(a==="clone"){var copy=clone(state.config.zones[i]);copy.name=safe(copy.name,"Kho")+" copy";state.config.zones.splice(i+1,0,copy)}else if(a==="delete"){if(state.config.zones.length<=1){DashboardSetupBridge.error("Cần giữ ít nhất một kho.");return}state.config.zones.splice(i,1)}render()});
  render();DashboardSetupBridge.start({onInit:initialize,onCollect:collect});
})();
