(function(){"use strict";
  var state={config:null,station:null,mode:"manual",region:1,prices:{},payload:{},onlineUpdated:null,stream:null,reconnect:null,logs:[],lastVersion:"",logFilter:"",dbAvailable:false};
  function id(v){return document.getElementById(v)}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function text(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}
  function num(v,f){var n=Number(v);return Number.isFinite(n)?n:Number(f||0)}
  function on(v){return /^(1|true|on|online|connected)$/i.test(String(v==null?"":v).trim())}
  function hydrate(raw){var c=window.ROSA_SIMULATOR_CONTEXT||{};return String(raw||"").replace(/<<sessionid>>/gi,text(c.sessionId,"IO123abcd@simulate")).replace(/<<syncid>>/gi,text(c.syncId,"SIM_SYNC"))}
  function parse(){try{return JSON.parse(hydrate(id("fuel-price-config").textContent))}catch(e){return null}}
  function read(field){var target=String(field||"").toLowerCase(),value=null;Object.keys(state.payload).some(function(k){if(k.toLowerCase()===target){value=state.payload[k];return true}return false});return value}
  function money(v){return Math.round(num(v,0)).toLocaleString("vi-VN")}
  function validPrice(v){v=Number(v);return Number.isInteger(v)&&v>0&&v<=99999}
  function fields(){var f=state.station.fields||{},out=[f.online,f.ackVersion,f.brightness,f.controllerTemp];Object.keys(f.prices||{}).forEach(function(k){out.push(f.prices[k])});return out.filter(Boolean)}
  function telemetryUrl(){var q=new URLSearchParams();q.set("fields",fields().join(","));return"/api/"+encodeURIComponent(state.station.sessionId)+"/"+encodeURIComponent(state.config.syncId)+"/iotelemetry?"+q}
  function streamUrl(){var q=new URLSearchParams();q.set("fields",fields().join(","));return"/api/"+encodeURIComponent(state.station.sessionId)+"/stream?"+q}
  function commandUrl(){var s=String(state.station.sessionId||""),p=s.indexOf("@");return p>0?"https://iot.ioeasy.com/cmd/"+encodeURIComponent(s.slice(0,p))+"?apiKey="+encodeURIComponent(s.slice(p+1)):""}
  function version(){var d=new Date(),pad=function(v){return String(v).padStart(2,"0")};return[d.getFullYear(),pad(d.getMonth()+1),pad(d.getDate()),pad(d.getHours()),pad(d.getMinutes()),pad(d.getSeconds())].join("")}
  function pricePayload(){return(state.config.products||[]).map(function(p){return p.code+"="+Math.round(num(state.prices[p.code],0))}).join("|")}
  function schedulePayload(){return(state.config.brightnessSchedule||[]).filter(function(x){return x.enabled!==false}).map(function(x){return String(Math.round(num(x.hour,0))).padStart(2,"0")+":"+String(Math.round(num(x.minute,0))).padStart(2,"0")+"="+Math.round(num(x.brightness,1))}).join("|")}
  function resolveTemplate(template,values){var result=String(template||"");Object.keys(values).forEach(function(k){result=result.split("{"+k+"}").join(String(values[k]))});var resolver=window.AIBridgeCommandTemplate;return resolver&&resolver.resolveCommandTemplate?resolver.resolveCommandTemplate(result):Promise.resolve(result)}
  function macroUrl(){return"/api/"+encodeURIComponent(state.station.sessionId)+"/"+encodeURIComponent(state.config.syncId)+"/iodata"}
  function postMacro(payload){return fetch(macroUrl(),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload||{})}).then(function(r){return r.json().catch(function(){return null}).then(function(data){if(!r.ok)throw new Error(data&&data.error||"Không thể truy cập cơ sở dữ liệu.");state.dbAvailable=true;return Array.isArray(data)?data:data&&Array.isArray(data.rows)?data.rows:[]})})}
  function requestId(prefix){return(prefix||"FP")+"-"+Date.now().toString(36).toUpperCase()+"-"+Math.random().toString(36).slice(2,7).toUpperCase()}
  function dbAudit(category,action,status,detail,payload,req){var a=state.config.audit||{},macro=a.writeMacro||"fuel-audit-write";return postMacro({macro:macro,category:category,action:action,status:status,request_id:req||requestId("AUD"),actor:"<<username>>",station_id:(state.config.ledSettings||{}).stationId||"default",detail:detail||"",payload_json:JSON.stringify(payload||{})}).then(function(){return loadDbLogs()}).catch(function(){return null})}
  function auditActionLabel(action){var labels={send_prices:"Gửi bảng giá",set_brightness:"Đặt độ sáng tức thời",set_brightness_schedule:"Cập nhật lịch độ sáng",send_led_settings:"Gửi cấu hình bảng LED",save_led_settings:"Lưu cài đặt bảng LED",board_led_on:"Bật toàn bảng LED",board_led_off:"Tắt toàn bảng LED",price_mode_manual:"Chọn nguồn nhập tay",price_mode_online:"Chọn nguồn Petrolimex",price_region:"Chọn vùng giá",fetch_online_prices:"Lấy giá Petrolimex",test:"Kiểm tra hệ thống"};return labels[action]||String(action||"Sự kiện hệ thống").replace(/_/g," ")}
  function commandSubject(action,values){values=values||{};if(action==="send_prices")return"bảng giá phiên bản "+text(values.version,"không rõ")+", nguồn "+(values.source==="online"?"Petrolimex":"nhập tay")+", Vùng "+text(values.region,"1")+" ["+String(values.payload||"").replace(/\|/g,"; ")+"]";if(action==="set_brightness")return"độ sáng tức thời "+text(values.value,"?")+"/10";if(action==="set_brightness_schedule")return"lịch độ sáng ["+String(values.payload||"").replace(/\|/g,"; ")+"]";if(action==="board_led_on")return"lệnh bật hiển thị toàn bảng LED";if(action==="board_led_off")return"lệnh tắt hiển thị toàn bảng LED";if(action==="send_led_settings"){var cfg={};String(values.payload||"").split("|").forEach(function(x){var i=x.indexOf("=");if(i>0)cfg[x.slice(0,i)]=x.slice(i+1)});return"cấu hình bảng LED: địa chỉ "+text(cfg.ADDR,"?")+", kênh "+text(cfg.CH,"?")+", "+(cfg.FACE==="one"?"1 mặt":"2 mặt cùng nội dung")+", quạt "+(cfg.FAN==="auto"?"tự động":"liên tục")+", kết nối "+text(cfg.LINK,"không rõ")+", các hàng ["+text(cfg.ROWS,"chưa có")+"]"}return auditActionLabel(action)}
  function commandAuditDetail(action,values,status,error){var subject=commandSubject(action,values);if(status==="pending")return"Đang gửi "+subject+" xuống thiết bị.";if(status==="success")return"Gateway đã nhận "+subject+".";return"Gửi "+subject+" thất bại: "+text(error,"Lỗi không xác định")}
  function toast(message,type){var n=document.createElement("div");n.className="fp-toast "+(type||"");n.textContent=message;id("fp-toasts").appendChild(n);setTimeout(function(){n.remove()},4200)}
  function logKey(){return"rosa-fuel-log-"+String(state.station&&state.station.sessionId||"station").replace(/[^a-z0-9_-]/gi,"_")}
  function saveLogs(){try{localStorage.setItem(logKey(),JSON.stringify(state.logs))}catch(e){}}
  function loadLogs(){try{var rows=JSON.parse(localStorage.getItem(logKey())||"[]");state.logs=Array.isArray(rows)?rows.map(function(x){return{time:new Date(x.time),message:String(x.message||""),type:String(x.type||"info")}}).filter(function(x){return!isNaN(x.time.getTime())}).slice(0,100):[]}catch(e){state.logs=[]}}
  function log(message,type){state.logs.unshift({time:new Date(),message:String(message),type:type||"info"});state.logs=state.logs.slice(0,100);saveLogs();renderLog()}
  function renderLog(){var box=id("fp-log");if(!box)return;box.innerHTML=state.logs.length?state.logs.map(function(x){return'<div class="fp-log-row" data-type="'+esc(x.type)+'"><time>'+x.time.toLocaleTimeString("vi-VN")+'</time><span>'+esc(x.message)+'</span></div>'}).join(""):'<div class="fp-log-empty">Chưa có sự kiện vận hành.</div>'}
  function validateAll(){var bad=(state.config.products||[]).filter(function(p){return!validPrice(state.prices[p.code])});if(bad.length)throw new Error("Giá "+bad.map(function(p){return p.label}).join(", ")+" phải là số nguyên từ 1 đến 99.999.")}
  function renderInputs(){id("fp-price-inputs").innerHTML=(state.config.products||[]).map(function(p){var automatic=p.onlineAvailable!==false,source=state.mode==="online"?(automatic?"Tự động từ Petrolimex":"API không cung cấp · nhập tay"):"Mã thiết bị: "+p.code;return'<div class="fp-price-input" style="--product-color:'+esc(p.color||"#38bdf8")+'"><i></i><label><span>'+esc(p.label)+'</span><small>'+esc(p.unit||"đồng/lít")+' · '+esc(source)+'</small></label><input type="number" min="1" max="99999" step="1" data-price-code="'+esc(p.code)+'" value="'+Math.round(num(state.prices[p.code],0))+'"'+(state.mode==="online"&&automatic?" disabled":"")+'></div>'}).join("")}
  function renderLed(){id("fp-led-board").innerHTML=(state.config.products||[]).map(function(p){var value=validPrice(state.prices[p.code])?String(Math.round(state.prices[p.code])).padStart(5,"0"):"-----";return'<div class="fp-led-row"><span class="fp-led-label" style="--product-color:'+esc(p.color||"#38bdf8")+'">'+esc(p.label)+' <small>'+esc((p.unit||"đồng/lít").replace("đồng/","/"))+'</small></span><strong class="fp-led-digits">'+value+'</strong></div>'}).join("")}
  function pricesMatch(){var f=state.station.fields&&state.station.fields.prices||{};return(state.config.products||[]).every(function(p){var actual=read(f[p.code]);return actual!=null&&Math.round(num(actual,-1))===Math.round(num(state.prices[p.code],-2))})}
  function renderStation(){var s=state.station,f=s.fields||{},online=on(read(f.online)),brightness=Math.max(1,Math.min(10,Math.round(num(read(f.brightness),7)))),temp=num(read(f.controllerTemp),0),ack=text(read(f.ackVersion),"Chưa có"),synced=pricesMatch();id("fp-station-name").textContent=s.name;id("fp-station-summary").textContent=(s.location||s.sessionId)+" · "+(online?"Thiết bị trực tuyến":"Mất kết nối thiết bị");id("fp-station-card").innerHTML='<div class="fp-single-head"><div><span class="fp-online-badge" data-online="'+online+'">'+(online?"TRỰC TUYẾN":"MẤT KẾT NỐI")+'</span><strong>'+esc(s.sessionId)+'</strong></div><div class="fp-sync" data-state="'+(synced?"synced":"pending")+'">'+(synced?"✓ Giá thiết bị đang hiển thị đã khớp":"Chưa xác nhận giá hiển thị khớp")+'</div></div><div class="fp-station-metrics"><div class="fp-metric"><span>Phiên bản phản hồi</span><strong>'+esc(ack)+'</strong></div><div class="fp-metric"><span>Độ sáng hiện tại</span><strong>'+brightness+'/10</strong></div><div class="fp-metric"><span>Nhiệt bộ điều khiển</span><strong>'+temp.toFixed(1)+' °C</strong></div></div><div class="fp-direct-brightness"><label>Chỉnh ngay <input type="range" min="1" max="10" value="'+brightness+'" id="fp-brightness-now"><strong id="fp-brightness-now-value">'+brightness+'</strong></label><button class="fp-button muted" id="fp-send-brightness-now">Gửi độ sáng ngay</button></div>';var alert=id("fp-alert");alert.hidden=online;alert.textContent=online?"":"⚠ Trạm đang không có tín hiệu trực tuyến. Chỉ gửi lệnh khi đã xác minh kết nối thiết bị."}
  function renderSchedule(){id("fp-schedule").innerHTML=(state.config.brightnessSchedule||[]).map(function(x,i){return'<div class="fp-schedule-row"><input type="checkbox" data-schedule-key="enabled" data-schedule-index="'+i+'"'+(x.enabled!==false?" checked":"")+'><span>Mốc '+(i+1)+'</span><label>Giờ<input type="number" min="0" max="23" value="'+Math.round(num(x.hour,0))+'" data-schedule-key="hour" data-schedule-index="'+i+'"></label><label>Phút<input type="number" min="0" max="59" value="'+Math.round(num(x.minute,0))+'" data-schedule-key="minute" data-schedule-index="'+i+'"></label><label>Độ sáng<input type="number" min="1" max="10" value="'+Math.round(num(x.brightness,1))+'" data-schedule-key="brightness" data-schedule-index="'+i+'"></label></div>'}).join("")}
  function renderMode(){var automatic=(state.config.products||[]).filter(function(p){return p.onlineAvailable!==false}).length;document.querySelectorAll("[data-price-mode]").forEach(function(b){b.classList.toggle("is-active",b.getAttribute("data-price-mode")===state.mode)});id("fp-online-tools").hidden=state.mode!=="online";id("fp-source-state").textContent=state.mode==="online"?"Petrolimex · "+automatic+" mặt hàng tự động":"Giá nhập tay";if(state.mode==="online")id("fp-source-note").textContent=state.onlineUpdated?"Đã cập nhật "+automatic+" mặt hàng lúc "+new Date(state.onlineUpdated).toLocaleString("vi-VN")+". Hãy kiểm tra trước khi gửi.":"Bấm “Lấy giá Petrolimex” để nạp toàn bộ "+automatic+" giá bán lẻ.";else id("fp-source-note").textContent="Nhập giá theo đơn vị đồng/lít và tối đa 5 chữ số cho mỗi dòng LED.";renderInputs();renderLed()}
  function render(){renderMode();renderStation();renderSchedule();renderLog()}
  function normalizeTitle(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/đ/g,"d").replace(/\s+/g," ").trim()}
  function fetchOnline(){var source=state.config.onlineSource||{},button=id("fp-fetch-online");button.disabled=true;button.textContent="Đang lấy giá...";log("Bắt đầu lấy giá từ Petrolimex Vùng "+state.region+".");return fetch(source.url,{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error("Nguồn Petrolimex trả lỗi "+r.status);return r.json()}).then(function(data){var rows=Array.isArray(data.Objects)?data.Objects:[],missing=[],updated=0;(state.config.products||[]).forEach(function(p){var row=rows.find(function(x){return normalizeTitle(x.Title)===normalizeTitle(p.officialTitle)});if(!row){missing.push(p.label);return}var value=state.region===2?row.Zone2Price:row.Zone1Price;if(!validPrice(Number(value)))missing.push(p.label);else{state.prices[p.code]=Number(value);updated++}if(row.LastModified&&(!state.onlineUpdated||new Date(row.LastModified)>new Date(state.onlineUpdated)))state.onlineUpdated=row.LastModified});if(missing.length)throw new Error("Không tìm thấy giá hợp lệ cho: "+missing.join(", "));toast("Đã nạp "+updated+" giá Petrolimex.");log("Đã nhận đủ "+updated+" giá online.","success");renderMode()}).catch(function(e){toast("Không lấy được giá online: "+e.message,"error");log("Lỗi lấy giá online: "+e.message,"error")}).finally(function(){button.disabled=false;button.textContent="Lấy giá Petrolimex"})}
  function openConfirm(){try{validateAll()}catch(e){toast(e.message,"error");log(e.message,"error");return}id("fp-confirm-copy").textContent="Bảng giá sẽ được gửi xuống thiết bị của "+state.station.name+". Sau khi gửi cần chờ phiên bản phản hồi và đối chiếu giá hiển thị.";id("fp-confirm-prices").innerHTML=(state.config.products||[]).map(function(p){return"<div><span>"+esc(p.label)+"</span><strong>"+money(state.prices[p.code])+" "+esc(p.unit||"đồng/lít")+"</strong></div>"}).join("");id("fp-confirm-check").checked=false;id("fp-confirm-send").disabled=true;id("fp-confirm-modal").hidden=false}
  function closeConfirm(){id("fp-confirm-modal").hidden=true}
  function sendPrices(){var v=version(),button=id("fp-confirm-send");button.disabled=true;button.textContent="Đang gửi...";state.lastVersion=v;log("Đang gửi bảng giá phiên bản "+v+" xuống thiết bị.");postCommand(state.station.commandTemplate,{version:v,payload:pricePayload(),region:state.region,source:state.mode}).then(function(){closeConfirm();toast("Đã gửi bảng giá "+v+".");log("Gateway đã nhận lệnh bảng giá "+v+". Chờ thiết bị phản hồi.","success");id("fp-preview-state").textContent="Đã gửi phiên bản "+v+" · đang chờ thiết bị phản hồi"}).catch(function(e){toast("Không gửi được bảng giá: "+e.message,"error");log("Gửi bảng giá thất bại: "+e.message,"error")}).finally(function(){button.textContent="Xác nhận gửi"})}
  function sendBrightness(){var value=Math.round(num(id("fp-brightness-now").value,7)),button=id("fp-send-brightness-now");button.disabled=true;log("Đang gửi độ sáng tức thời "+value+"/10.");postCommand(state.station.brightnessTemplate,{value:value}).then(function(){toast("Đã gửi độ sáng "+value+"/10.");log("Đã gửi độ sáng tức thời "+value+"/10.","success")}).catch(function(e){toast("Không gửi được độ sáng: "+e.message,"error");log("Gửi độ sáng thất bại: "+e.message,"error")}).finally(function(){button.disabled=false})}
  function sendSchedule(){var payload=schedulePayload(),button=id("fp-send-schedule");if(!payload){toast("Cần bật ít nhất một mốc độ sáng.","error");return}button.disabled=true;log("Đang gửi lịch độ sáng: "+payload+".");postCommand(state.station.scheduleTemplate,{payload:payload}).then(function(){toast("Đã gửi lịch độ sáng.");log("Gateway đã nhận lịch độ sáng "+payload+".","success")}).catch(function(e){toast("Không gửi được lịch: "+e.message,"error");log("Gửi lịch độ sáng thất bại: "+e.message,"error")}).finally(function(){button.disabled=false})}
  function apply(payload){state.payload=Object.assign({},state.payload,payload||{});renderStation()}
  function snapshot(){return fetch(telemetryUrl(),{cache:"no-store"}).then(function(r){return r.ok?r.json():null}).then(function(p){var c=p&&p.c2;if(c){apply(c.payload);log("Đã tải trạng thái ban đầu của thiết bị.","success")}}).catch(function(e){log("Không tải được trạng thái ban đầu: "+e.message,"error")})}
  function connect(){if(typeof EventSource==="undefined")return;try{var source=new EventSource(streamUrl());state.stream=source;source.onopen=function(){log("Kênh realtime đã kết nối.","success")};source.onmessage=function(e){try{var d=JSON.parse(e.data);if(d.type==="telemetry")apply(d.payload)}catch(x){}};source.onerror=function(){source.close();state.stream=null;log("Mất kênh realtime, đang kết nối lại.","warn");clearTimeout(state.reconnect);state.reconnect=setTimeout(connect,3500)}}catch(e){log("Không mở được kênh realtime: "+e.message,"error")}}
  function bind(){document.addEventListener("input",function(e){if(e.target.matches("[data-price-code]")){state.prices[e.target.getAttribute("data-price-code")]=Number(e.target.value);renderLed()}else if(e.target.id==="fp-brightness-now")id("fp-brightness-now-value").textContent=e.target.value;else if(e.target.matches("[data-schedule-key]")){var x=state.config.brightnessSchedule[Number(e.target.getAttribute("data-schedule-index"))],key=e.target.getAttribute("data-schedule-key");x[key]=key==="enabled"?e.target.checked:Number(e.target.value)}});document.addEventListener("click",function(e){var mode=e.target.closest("[data-price-mode]");if(mode){state.mode=mode.getAttribute("data-price-mode");log("Chuyển nguồn giá sang "+(state.mode==="online"?"Online":"Nhập số")+".");renderMode();return}if(e.target.id==="fp-send-brightness-now")sendBrightness()});id("fp-region").onchange=function(){state.region=Number(this.value)||1;state.onlineUpdated=null;log("Chọn giá Petrolimex Vùng "+state.region+".");renderMode()};id("fp-fetch-online").onclick=fetchOnline;id("fp-source-link").href=(state.config.onlineSource||{}).homepage||"https://www.petrolimex.com.vn/";id("fp-open-confirm").onclick=openConfirm;id("fp-cancel-send").onclick=closeConfirm;id("fp-confirm-check").onchange=function(){id("fp-confirm-send").disabled=!this.checked};id("fp-confirm-send").onclick=sendPrices;id("fp-confirm-modal").onclick=function(e){if(e.target===this)closeConfirm()};id("fp-send-schedule").onclick=sendSchedule;id("fp-clear-log").onclick=function(){state.logs=[];saveLogs();renderLog()}}
  function ensureLedSettings(){
    state.config.ledSettings=state.config.ledSettings||{stationId:"default",controllerAddress:1,rfChannel:1,faceMode:"two_same",fanMode:"continuous",transport:"2.4g_usb_uart"};
    state.config.audit=state.config.audit||{writeMacro:"fuel-audit-write",listMacro:"fuel-audit-list",clearMacro:"fuel-audit-clear",settingsStateMacro:"fuel-settings-state",settingsSaveMacro:"fuel-settings-save"};
    state.station.settingsTemplate=state.station.settingsTemplate||'LEDCONFIG,{payload},"<<username>>"';
    (state.config.products||[]).forEach(function(p){if(p.displayEnabled===undefined)p.displayEnabled=true;if(!p.brightness)p.brightness=7});
  }
  function renderLed(){
    var products=state.config.products||[];
    id("fp-led-board").innerHTML=products.map(function(p){
      var active=p.displayEnabled!==false,value=active&&validPrice(state.prices[p.code])?String(Math.round(state.prices[p.code])).padStart(5,"0"):active?"-----":"OFF";
      return'<div class="fp-led-row'+(active?'':' is-off')+'"><span class="fp-led-label" style="--product-color:'+esc(p.color||"#38bdf8")+'">'+esc(p.label)+' <small>'+esc((p.unit||"đồng/lít").replace("đồng/","/"))+'</small></span><strong class="fp-led-digits">'+value+'</strong></div>';
    }).join("");
    var allOn=products.length&&products.every(function(p){return p.displayEnabled!==false}),allOff=products.length&&products.every(function(p){return p.displayEnabled===false});
    if(id("fp-board-show"))id("fp-board-show").disabled=!!allOn;
    if(id("fp-board-off"))id("fp-board-off").disabled=!!allOff;
  }
  function renderLedSettings(){
    ensureLedSettings();var s=state.config.ledSettings;
    id("fp-controller-address").value=s.controllerAddress;id("fp-rf-channel").value=s.rfChannel;id("fp-face-mode").value=s.faceMode;id("fp-fan-mode").value=s.fanMode;id("fp-transport").value=s.transport;
    id("fp-row-settings").innerHTML=(state.config.products||[]).map(function(p,i){var active=p.displayEnabled!==false;return'<div class="fp-row-setting'+(active?'':' is-off')+'"><label class="fp-row-toggle"><input type="checkbox" data-led-row-enabled="'+i+'" '+(active?'checked':'')+'><span><strong>'+esc(p.label)+'</strong><small>'+(active?'Đang hiển thị':'Đang tắt')+'</small></span></label><label class="fp-row-brightness">Độ sáng riêng<input type="number" min="1" max="10" value="'+Math.round(num(p.brightness,7))+'" data-led-row-brightness="'+i+'"></label></div>'}).join("");
  }
  function collectLedSettings(){
    ensureLedSettings();var s=state.config.ledSettings;
    s.controllerAddress=Math.max(1,Math.min(255,Math.round(num(id("fp-controller-address").value,1))));
    s.rfChannel=Math.max(1,Math.min(125,Math.round(num(id("fp-rf-channel").value,1))));
    s.faceMode=id("fp-face-mode").value==="one"?"one":"two_same";
    s.fanMode=id("fp-fan-mode").value==="auto"?"auto":"continuous";
    s.transport=id("fp-transport").value==="usb_uart"?"usb_uart":"2.4g_usb_uart";
    document.querySelectorAll("[data-led-row-enabled]").forEach(function(n){state.config.products[Number(n.getAttribute("data-led-row-enabled"))].displayEnabled=n.checked});
    document.querySelectorAll("[data-led-row-brightness]").forEach(function(n){state.config.products[Number(n.getAttribute("data-led-row-brightness"))].brightness=Math.max(1,Math.min(10,Math.round(num(n.value,7))))});
  }
  function ledRows(){return(state.config.products||[]).map(function(p){return{code:p.code,enabled:p.displayEnabled!==false?1:0,brightness:Math.round(num(p.brightness,7))}})}
  function ledSettingsDescription(){var s=state.config.ledSettings,rows=ledRows().map(function(r){return r.code+" "+(r.enabled?"bật":"tắt")+" "+r.brightness+"/10"}).join("; ");return"địa chỉ "+s.controllerAddress+", kênh "+s.rfChannel+", "+(s.faceMode==="one"?"1 mặt":"2 mặt cùng nội dung")+", quạt "+(s.fanMode==="auto"?"tự động":"liên tục")+", kết nối "+s.transport+"; các hàng: "+rows}
  function ledSettingsPayload(){collectLedSettings();var s=state.config.ledSettings;return"ADDR="+s.controllerAddress+"|CH="+s.rfChannel+"|FACE="+s.faceMode+"|FAN="+s.fanMode+"|LINK="+s.transport+"|ROWS="+ledRows().map(function(r){return r.code+":"+r.enabled+":"+r.brightness}).join(",")}
  function saveLedSettings(){
    var button=id("fp-save-settings"),s=state.config.ledSettings,a=state.config.audit||{},req=requestId("SET");collectLedSettings();button.disabled=true;
    var detail="Đã lưu cài đặt bảng LED: "+ledSettingsDescription()+".";
    return postMacro({macro:a.settingsSaveMacro||"fuel-settings-save",station_id:s.stationId||"default",controller_address:s.controllerAddress,rf_channel:s.rfChannel,face_mode:s.faceMode,fan_mode:s.fanMode,transport:s.transport,rows_json:JSON.stringify(ledRows()),request_id:req,actor:"<<username>>",detail:detail,payload_json:JSON.stringify(s)}).then(function(){toast("Đã lưu cài đặt vào cơ sở dữ liệu.");return loadDbLogs()}).catch(function(e){toast("Không lưu được cài đặt: "+e.message,"error");dbAudit("setting","save_led_settings","error","Lưu cài đặt bảng LED thất bại: "+e.message+". Cấu hình: "+ledSettingsDescription(),s,req);throw e}).finally(function(){button.disabled=false});
  }
  function sendLedSettings(){
    var button=id("fp-send-settings"),payload=ledSettingsPayload();button.disabled=true;
    return saveLedSettings().then(function(){return postCommand(state.station.settingsTemplate,{payload:payload})}).then(function(){toast("Đã gửi cài đặt bảng LED xuống thiết bị.")}).catch(function(e){toast("Không gửi được cài đặt: "+e.message,"error")}).finally(function(){button.disabled=false});
  }
  function setBoardEnabled(enabled){
    ensureLedSettings();(state.config.products||[]).forEach(function(p){p.displayEnabled=!!enabled});renderLed();renderLedSettings();
    var payload=ledSettingsPayload(),detail=enabled?"Bật hiển thị toàn bảng LED":"Tắt hiển thị toàn bảng LED";
    return saveLedSettings().then(function(){return postCommand(state.station.settingsTemplate,{payload:payload,state:enabled?"ON":"OFF"})}).then(function(){toast(detail+" thành công.")}).catch(function(e){toast(detail+" thất bại: "+e.message,"error")});
  }
  function openSettings(){id("fp-settings-page").hidden=false;document.body.classList.add("fp-settings-open");setTimeout(function(){id("fp-controller-address").focus()},0)}
  function closeSettings(){id("fp-settings-page").hidden=true;document.body.classList.remove("fp-settings-open")}
  function loadDbSettings(){
    var a=state.config.audit||{},s=state.config.ledSettings;
    return postMacro({macro:a.settingsStateMacro||"fuel-settings-state",station_id:s.stationId||"default"}).then(function(rows){
      (rows||[]).forEach(function(r){if(r.row_type==="controller"){s.controllerAddress=Number(r.controller_address)||1;s.rfChannel=Number(r.rf_channel)||1;s.faceMode=r.face_mode||"two_same";s.fanMode=r.fan_mode||"continuous";s.transport=r.transport||"2.4g_usb_uart"}else if(r.row_type==="row"){var p=(state.config.products||[]).filter(function(x){return x.code===r.product_code})[0];if(p){p.displayEnabled=Number(r.enabled)!==0;p.brightness=Number(r.brightness)||7}}});renderLedSettings();renderLed();
    }).catch(function(){renderLedSettings();renderLed()});
  }
  function clearDbLogs(){var a=state.config.audit||{};return postMacro({macro:a.clearMacro||"fuel-audit-clear",station_id:(state.config.ledSettings||{}).stationId||"default"}).then(function(){state.logs=[];renderLog();toast("Đã xóa log trong cơ sở dữ liệu.")}).catch(function(e){toast("Không xóa được log: "+e.message,"error")})}
  function postCommand(template,values){
    var url=commandUrl(),action=template===state.station.commandTemplate?"send_prices":template===state.station.brightnessTemplate?"set_brightness":template===state.station.scheduleTemplate?"set_brightness_schedule":template===state.station.settingsTemplate?(values&&values.state==="ON"?"board_led_on":values&&values.state==="OFF"?"board_led_off":"send_led_settings"):"send_command",req=requestId("CMD");
    if(!url||!template)return Promise.reject(new Error("Thiếu Device key hoặc mẫu lệnh."));
    dbAudit("control",action,"pending",commandAuditDetail(action,values,"pending"),values,req);
    return resolveTemplate(template,values).then(function(cmd){return fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cmd:cmd})}).then(function(r){if(!r.ok)throw new Error("Gateway từ chối lệnh");dbAudit("control",action,"success",commandAuditDetail(action,values,"success"),values,req);return cmd})}).catch(function(e){dbAudit("control",action,"error",commandAuditDetail(action,values,"error",e.message),values,req);throw e});
  }
  function initExtended(){
    if(!state.config||!state.station)return;ensureLedSettings();renderLedSettings();
    id("fp-save-settings").onclick=saveLedSettings;id("fp-send-settings").onclick=sendLedSettings;
    id("fp-open-settings").onclick=openSettings;id("fp-close-settings").onclick=closeSettings;
    id("fp-board-show").onclick=function(){setBoardEnabled(true)};id("fp-board-off").onclick=function(){setBoardEnabled(false)};
    document.addEventListener("change",function(e){if(!e.target.matches("[data-led-row-enabled]"))return;var i=Number(e.target.getAttribute("data-led-row-enabled")),p=state.config.products[i];if(!p)return;p.displayEnabled=e.target.checked;var card=e.target.closest(".fp-row-setting"),status=card&&card.querySelector("small");if(card)card.classList.toggle("is-off",!e.target.checked);if(status)status.textContent=e.target.checked?"Đang hiển thị":"Đang tắt";renderLed()});
    id("fp-settings-page").onclick=function(e){if(e.target===this)closeSettings()};document.addEventListener("keydown",function(e){if(e.key==="Escape"&&!id("fp-settings-page").hidden)closeSettings()});
    id("fp-log-filter").value=state.logFilter;id("fp-log-filter").onchange=function(){state.logFilter=this.value;loadDbLogs()};
    id("fp-clear-log").onclick=clearDbLogs;
    loadDbSettings().then(loadDbLogs);
  }
  function loadDbLogs(){
    var a=state.config.audit||{};
    return postMacro({macro:a.listMacro||"fuel-audit-list",category:state.logFilter||"",limit:150}).then(function(rows){
      state.logs=(rows||[]).filter(function(x){return x&&x.id!=null}).map(function(x){return{time:new Date(Number(x.ts)||Date.now()),message:String(x.detail||x.action||""),type:x.status==="error"?"error":x.status==="warning"?"warn":x.status==="success"?"success":"info",category:String(x.category||"system"),action:String(x.action||""),requestId:String(x.request_id||"")}});
      renderLog();return rows;
    }).catch(function(){state.dbAvailable=false;renderLog();return[]});
  }
  function renderLog(){
    var box=id("fp-log");if(!box)return;
    var rows=(state.logs||[]).filter(function(x){return!state.logFilter||x.category===state.logFilter});
    box.innerHTML=rows.length?rows.map(function(x){return'<div class="fp-log-row" data-type="'+esc(x.type)+'"><time>'+x.time.toLocaleString("vi-VN")+'</time><span><b>'+esc(x.category==="control"?"ĐIỀU KHIỂN":x.category==="setting"?"CÀI ĐẶT":x.category==="price_source"?"NGUỒN GIÁ":"HỆ THỐNG")+'</b><strong class="fp-log-action">'+esc(auditActionLabel(x.action))+'</strong><span class="fp-log-detail">'+esc(x.message)+'</span>'+(x.requestId?'<small>Mã yêu cầu: '+esc(x.requestId)+'</small>':'')+'</span></div>'}).join(""):'<div class="fp-log-empty">Chưa có sự kiện phù hợp.</div>';
  }

  /* Operational safety layer: source gating, device acknowledgement, drafts and auditable commands. */
  var ONLINE_BATCH_MAX_AGE=30*60*1000,TELEMETRY_MAX_AGE=30*1000,REQUEST_TIMEOUT=15*1000;
  function cloneValue(v){return JSON.parse(JSON.stringify(v==null?{}:v))}
  function fetchTimeout(url,options,timeout){var controller=typeof AbortController!=="undefined"?new AbortController():null,timer=controller?setTimeout(function(){controller.abort()},timeout||REQUEST_TIMEOUT):null,opts=Object.assign({},options||{});if(controller)opts.signal=controller.signal;return fetch(url,opts).catch(function(e){if(e&&e.name==="AbortError")throw new Error("Quá thời gian chờ phản hồi");throw e}).finally(function(){if(timer)clearTimeout(timer)})}
  function fields(){var f=state.station.fields||{};return[f.online,f.ackVersion,f.settingsAckVersion,f.brightness,f.controllerTemp].filter(Boolean)}
  function postMacro(payload){return fetchTimeout(macroUrl(),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload||{})}).then(function(r){return r.json().catch(function(){return null}).then(function(data){if(!r.ok)throw new Error(data&&data.error||"Không thể truy cập cơ sở dữ liệu.");state.dbAvailable=true;return Array.isArray(data)?data:data&&Array.isArray(data.rows)?data.rows:[]})})}
  function actorName(){var resolver=window.AIBridgeCommandTemplate;return resolver&&resolver.getSignedInUser?resolver.getSignedInUser().then(function(u){return text(u&&u.username,u&&u.email||"Người dùng ROSA")}):Promise.resolve("Người dùng ROSA")}
  function dbAudit(category,action,status,detail,payload,req){var a=state.config.audit||{},macro=a.writeMacro||"fuel-audit-write";return actorName().then(function(actor){return postMacro({macro:macro,category:category,action:action,status:status,request_id:req||requestId("AUD"),actor:actor,station_id:(state.config.ledSettings||{}).stationId||"default",detail:detail||"",payload_json:JSON.stringify(payload||{})})}).then(function(){return loadDbLogs().catch(function(){return null})})}
  function auditSoft(category,action,status,detail,payload,req){return dbAudit(category,action,status,detail,payload,req).catch(function(e){state.dbAvailable=false;toast("Cảnh báo: chưa ghi được nhật ký - "+e.message,"error");return null})}
  function auditActionLabel(action){var labels={send_prices:"Gửi bảng giá",set_brightness:"Đặt độ sáng tức thời",set_brightness_schedule:"Cập nhật lịch độ sáng",send_led_settings:"Gửi cấu hình bảng LED",save_led_settings:"Lưu cài đặt bảng LED",board_led_on:"Bật toàn bảng LED",board_led_off:"Tắt toàn bảng LED",price_mode_manual:"Chọn nguồn nhập tay",price_mode_online:"Chọn nguồn Petrolimex",price_region:"Chọn vùng giá",fetch_online_prices:"Lấy giá Petrolimex",clear_audit_logs:"Xóa nhật ký",test:"Kiểm tra hệ thống"};return labels[action]||String(action||"Sự kiện hệ thống").replace(/_/g," ")}
  function operationalKey(){return"rosa-fuel-operation-"+String(state.station&&state.station.sessionId||"station").replace(/[^a-z0-9_-]/gi,"_")}
  function saveOperationalState(){try{localStorage.setItem(operationalKey(),JSON.stringify({pendingPrice:state.pendingPrice||null,pendingSettings:state.pendingSettings||null,lastVersion:state.lastVersion||""}))}catch(e){}}
  function initOperationalState(){state.manualPrices=cloneValue(state.prices);state.onlineBatches={};state.lastSeenAt=0;state.streamConnected=false;state.settingsDraft=null;state.settingsDirty=false;state.settingsSavedOnly=false;state.demoMode=!!window.ROSA_SIMULATOR_CONTEXT||(/^(localhost|127\.0\.0\.1)$/i.test(location.hostname)&&/@simulate$/i.test(String(state.station.sessionId||"")));state.demoConnected=true;try{var x=JSON.parse(localStorage.getItem(operationalKey())||"{}");state.pendingPrice=x.pendingPrice||null;state.pendingSettings=x.pendingSettings||null;state.lastVersion=text(x.lastVersion,state.pendingPrice&&state.pendingPrice.version||"")}catch(e){}if(!state.heartbeat)state.heartbeat=setInterval(function(){if(state.config){renderStation();renderSettingsState()}},5000)}
  function demoTelemetry(){var f=state.station.fields||{},payload={};payload[f.online]="ON";payload[f.brightness]=num(read(f.brightness),7)||7;payload[f.controllerTemp]=36.4+Math.round(Math.random()*8)/10;if(state.pendingPrice&&state.pendingPrice.version)payload[f.ackVersion]=state.pendingPrice.version;if(state.pendingSettings&&state.pendingSettings.version)payload[f.settingsAckVersion]=state.pendingSettings.version;return payload}
  function demoHeartbeat(){if(!state.demoMode||!state.demoConnected)return;apply(demoTelemetry())}
  function startDemo(){if(!state.demoMode)return;demoHeartbeat();if(!state.demoHeartbeat)state.demoHeartbeat=setInterval(demoHeartbeat,8000)}
  function demoAckPrice(v){if(!state.demoMode||!state.demoConnected)return;setTimeout(function(){if(!state.demoConnected)return;var f=state.station.fields||{},payload={};payload[f.online]="ON";payload[f.ackVersion]=v;apply(payload);id("fp-preview-state").textContent="Thiết bị mô phỏng đã ACK phiên bản "+v;toast("Thiết bị mô phỏng đã ACK bảng giá.")},900)}
  function demoAckSettings(v){if(!state.demoMode||!state.demoConnected)return;setTimeout(function(){if(!state.demoConnected)return;var f=state.station.fields||{},payload={};payload[f.online]="ON";payload[f.settingsAckVersion]=v;apply(payload);toast("Thiết bị mô phỏng đã ACK cấu hình "+v+".")},900)}
  function version(){var d=new Date(),pad=function(v){return String(v).padStart(2,"0")},candidate=[d.getFullYear(),pad(d.getMonth()+1),pad(d.getDate()),pad(d.getHours()),pad(d.getMinutes()),pad(d.getSeconds())].join("");if(state.lastVersion&&Number(candidate)<=Number(state.lastVersion))candidate=String(Number(state.lastVersion)+1);state.lastVersion=candidate;saveOperationalState();return candidate}
  function deviceOnline(){var f=state.station&&state.station.fields||{};return!!(state.lastSeenAt&&Date.now()-state.lastSeenAt<=TELEMETRY_MAX_AGE&&on(read(f.online)))}
  function requireOnline(){if(deviceOnline())return true;toast("Thiết bị đang offline hoặc dữ liệu đã quá 30 giây. Không gửi lệnh.","error");return false}
  function currentOnlineBatch(){return state.onlineBatches&&state.onlineBatches[String(state.region)]||null}
  function onlineBatchValid(){var b=currentOnlineBatch();return!!(b&&b.region===state.region&&Date.now()-b.fetchedAt<=ONLINE_BATCH_MAX_AGE)}
  function pricesEqual(a,b){return(state.config.products||[]).every(function(p){return validPrice(a&&a[p.code])&&Math.round(a[p.code])===Math.round(b&&b[p.code])})}
  function sourceReady(){return state.mode==="manual"?(state.config.products||[]).every(function(p){return validPrice(state.prices[p.code])}):onlineBatchValid()&&pricesEqual(state.prices,currentOnlineBatch().prices)}
  function priceApplyState(){var f=state.station.fields||{},ack=text(read(f.ackVersion),""),pending=state.pendingPrice;if(pending){if(ack===String(pending.version)){pending.status="applied";saveOperationalState();return{state:"synced",text:"✓ Thiết bị đã ACK bảng giá phiên bản "+pending.version}}return{state:"waiting",text:"Đang chờ thiết bị ACK bảng giá "+pending.version}}if(ack)return{state:"reported",text:"Thiết bị đã phản hồi phiên bản bảng giá "+ack};return{state:"pending",text:"Chưa có phiên bản bảng giá được thiết bị xác nhận"}}
  function renderInputs(){id("fp-price-inputs").innerHTML=(state.config.products||[]).map(function(p){var automatic=p.onlineAvailable!==false,source=state.mode==="online"?(automatic?"Chờ lô Petrolimex đã xác thực":"API không cung cấp · nhập tay"):("Mã thiết bị: "+p.code),value=validPrice(state.prices[p.code])?Math.round(state.prices[p.code]):"";return'<div class="fp-price-input" style="--product-color:'+esc(p.color||"#38bdf8")+'"><i></i><label><span>'+esc(p.label)+'</span><small>'+esc(p.unit||"đồng/lít")+' · '+esc(source)+'</small></label><input type="number" min="1" max="99999" step="1" data-price-code="'+esc(p.code)+'" value="'+value+'"'+(state.mode==="online"&&automatic?" disabled":"")+'></div>'}).join("")}
  function renderLed(){var products=state.config.products||[];id("fp-led-board").innerHTML=products.map(function(p){var active=p.displayEnabled!==false,value=active&&validPrice(state.prices[p.code])?String(Math.round(state.prices[p.code])).padStart(5,"0"):active?"-----":"OFF";return'<div class="fp-led-row'+(active?'':' is-off')+'"><span class="fp-led-label" style="--product-color:'+esc(p.color||"#38bdf8")+'">'+esc(p.label)+' <small>'+esc((p.unit||"đồng/lít").replace("đồng/","/"))+'</small></span><strong class="fp-led-digits">'+value+'</strong></div>'}).join("");var online=deviceOnline(),allOn=products.length&&products.every(function(p){return p.displayEnabled!==false}),allOff=products.length&&products.every(function(p){return p.displayEnabled===false});if(id("fp-board-show"))id("fp-board-show").disabled=!online||!!allOn;if(id("fp-board-off"))id("fp-board-off").disabled=!online||!!allOff}
  function renderMode(){var automatic=(state.config.products||[]).filter(function(p){return p.onlineAvailable!==false}).length,batch=currentOnlineBatch();document.querySelectorAll("[data-price-mode]").forEach(function(b){b.classList.toggle("is-active",b.getAttribute("data-price-mode")===state.mode)});id("fp-online-tools").hidden=state.mode!=="online";id("fp-source-state").textContent=state.mode==="online"?"Petrolimex · "+automatic+" mặt hàng":"Giá nhập tay";if(state.mode==="online")id("fp-source-note").textContent=onlineBatchValid()?"Lô Vùng "+state.region+" lấy lúc "+new Date(batch.fetchedAt).toLocaleString("vi-VN")+" · nguồn cập nhật "+new Date(batch.sourceUpdated).toLocaleString("vi-VN")+" · có hiệu lực 30 phút.":"Chưa có lô giá Petrolimex hợp lệ cho Vùng "+state.region+". Bắt buộc lấy đủ giá trước khi gửi.";else id("fp-source-note").textContent="Nhập giá theo đơn vị đồng/lít và tối đa 5 chữ số cho mỗi dòng LED.";renderInputs();renderLed();renderStation()}
  function renderStation(){var s=state.station,f=s.fields||{},online=deviceOnline(),brightness=Math.max(1,Math.min(10,Math.round(num(read(f.brightness),7)))),temp=num(read(f.controllerTemp),0),ack=text(read(f.ackVersion),"Chưa có"),sync=priceApplyState(),last=state.lastSeenAt?new Date(state.lastSeenAt).toLocaleTimeString("vi-VN"):"chưa nhận";id("fp-station-name").textContent=s.name;id("fp-station-summary").textContent=(s.location||s.sessionId)+" · "+(online?"Thiết bị trực tuyến":"Mất kết nối hoặc dữ liệu quá hạn");id("fp-station-card").innerHTML='<div class="fp-single-head"><div><span class="fp-online-badge" data-online="'+online+'">'+(online?"TRỰC TUYẾN":"MẤT KẾT NỐI")+'</span><strong>'+esc(s.sessionId)+'</strong><small class="fp-last-seen">Dữ liệu cuối: '+esc(last)+'</small></div><div class="fp-sync" data-state="'+sync.state+'">'+esc(sync.text)+'</div></div><div class="fp-station-metrics"><div class="fp-metric"><span>Phiên bản phản hồi</span><strong>'+esc(ack)+'</strong></div><div class="fp-metric"><span>Độ sáng hiện tại</span><strong>'+brightness+'/10</strong></div><div class="fp-metric"><span>Nhiệt bộ điều khiển</span><strong>'+temp.toFixed(1)+' °C</strong></div></div><div class="fp-direct-brightness"><label>Chỉnh ngay <input type="range" min="1" max="10" value="'+brightness+'" id="fp-brightness-now" '+(online?'':'disabled')+'><strong id="fp-brightness-now-value">'+brightness+'</strong></label><button class="fp-button muted" id="fp-send-brightness-now" '+(online?'':'disabled')+'>Gửi độ sáng ngay</button></div>';var alert=id("fp-alert");alert.hidden=online;alert.textContent=online?"":"⚠ Thiết bị không có telemetry mới trong 30 giây. Mọi lệnh điều khiển đã bị khóa.";if(id("fp-open-confirm")){id("fp-open-confirm").disabled=!online||!sourceReady();id("fp-open-confirm").title=!online?"Thiết bị đang offline":!sourceReady()?"Nguồn giá chưa hợp lệ hoặc đã hết hạn":""}if(id("fp-send-schedule"))id("fp-send-schedule").disabled=!online;if(id("fp-send-settings"))id("fp-send-settings").disabled=!online;renderLed()}
  function validateAll(){var bad=(state.config.products||[]).filter(function(p){return!validPrice(state.prices[p.code])});if(bad.length)throw new Error("Giá "+bad.map(function(p){return p.label}).join(", ")+" phải là số nguyên từ 1 đến 99.999.");if(state.mode==="online"&&!onlineBatchValid())throw new Error("Phải lấy lại đủ giá Petrolimex đúng Vùng "+state.region+" trước khi gửi.");if(state.mode==="online"&&!pricesEqual(state.prices,currentOnlineBatch().prices))throw new Error("Lô giá Online đã thay đổi hoặc không còn nguyên vẹn.");if(!deviceOnline())throw new Error("Thiết bị đang offline hoặc telemetry đã quá 30 giây.")}
  function fetchOnline(){
    var source=state.config.onlineSource||{},button=id("fp-fetch-online"),req=requestId("SRC"),requestedRegion=state.region,fetchSeq=(state.onlineFetchSeq||0)+1;
    state.onlineFetchSeq=fetchSeq;
    state.prices={};
    button.disabled=true;
    button.textContent="Đang lấy giá...";
    renderMode();
    auditSoft("price_source","fetch_online_prices","pending","Bắt đầu lấy giá Petrolimex Vùng "+requestedRegion+".",{region:requestedRegion},req);
    return fetchTimeout(source.url,{cache:"no-store"}).then(function(r){
      if(!r.ok)throw new Error("Nguồn Petrolimex trả lỗi "+r.status);
      return r.json();
    }).then(function(data){
      var rows=Array.isArray(data.Objects)?data.Objects:[],missing=[],staged={},sourceUpdated=0;
      (state.config.products||[]).forEach(function(p){
        var row=rows.find(function(x){return normalizeTitle(x.Title)===normalizeTitle(p.officialTitle)}),value=row&&(requestedRegion===2?row.Zone2Price:row.Zone1Price);
        if(!row||!validPrice(Number(value)))missing.push(p.label);
        else{staged[p.code]=Number(value);var t=Date.parse(row.LastModified||"");if(Number.isFinite(t))sourceUpdated=Math.max(sourceUpdated,t)}
      });
      if(missing.length)throw new Error("Không tìm thấy giá hợp lệ cho: "+missing.join(", "));
      var batch={region:requestedRegion,fetchedAt:Date.now(),sourceUpdated:sourceUpdated||Date.now(),prices:staged};
      state.onlineBatches[String(requestedRegion)]=batch;
      if(state.mode==="online"&&state.region===requestedRegion&&fetchSeq===state.onlineFetchSeq){state.onlineUpdated=new Date(batch.sourceUpdated).toISOString();state.prices=cloneValue(staged);toast("Đã tự động nạp đủ giá Petrolimex Vùng "+requestedRegion+".")}
      auditSoft("price_source","fetch_online_prices","success","Đã lấy đủ "+Object.keys(staged).length+" giá Petrolimex Vùng "+requestedRegion+"; nguồn cập nhật "+new Date(batch.sourceUpdated).toLocaleString("vi-VN")+".",{region:requestedRegion,prices:staged,source_updated:batch.sourceUpdated},req);
      renderMode();
    }).catch(function(e){
      auditSoft("price_source","fetch_online_prices","error","Lấy giá Petrolimex Vùng "+requestedRegion+" thất bại: "+e.message,{region:requestedRegion},req);
      if(state.mode==="online"&&state.region===requestedRegion&&fetchSeq===state.onlineFetchSeq){state.prices={};toast("Không lấy được giá online: "+e.message,"error");renderMode()}
    }).finally(function(){if(fetchSeq===state.onlineFetchSeq){button.disabled=false;button.textContent="Lấy lại giá Petrolimex"}})
  }
  function openConfirm(){try{validateAll()}catch(e){toast(e.message,"error");return}var batch=currentOnlineBatch();id("fp-confirm-copy").textContent="Dashboard gửi bảng giá một chiều xuống thiết bị và chỉ đánh dấu áp dụng khi nhận ACK đúng phiên bản.";id("fp-confirm-meta").textContent=state.mode==="online"?"Nguồn: Petrolimex · Vùng "+state.region+" · lấy lúc "+new Date(batch.fetchedAt).toLocaleString("vi-VN")+" · áp dụng ngay":"Nguồn: nhập tay · áp dụng ngay";id("fp-confirm-prices").innerHTML=(state.config.products||[]).map(function(p){return'<div><span>'+esc(p.label)+'<small>Gửi xuống thiết bị</small></span><strong>'+money(state.prices[p.code])+' '+esc(p.unit||"đồng/lít")+'</strong></div>'}).join("");id("fp-confirm-check").checked=false;id("fp-confirm-send").disabled=true;id("fp-confirm-modal").hidden=false}
  function sendPrices(){try{validateAll()}catch(e){toast(e.message,"error");return}var v=version(),button=id("fp-confirm-send"),snapshot=cloneValue(state.prices);button.disabled=true;button.textContent="Đang gửi...";postCommand(state.station.commandTemplate,{version:v,payload:(state.config.products||[]).map(function(p){return p.code+"="+Math.round(snapshot[p.code])}).join("|"),region:state.region,source:state.mode}).then(function(){state.pendingPrice={version:v,prices:snapshot,source:state.mode,region:state.region,sentAt:Date.now(),status:"waiting"};saveOperationalState();closeConfirm();toast("Gateway đã nhận bảng giá "+v+". Đang chờ thiết bị ACK.");id("fp-preview-state").textContent="Đã gửi "+v+" · chờ ACK phiên bản";renderStation();demoAckPrice(v)}).catch(function(e){toast("Không gửi được bảng giá: "+e.message,"error")}).finally(function(){button.textContent="Xác nhận gửi"})}
  function validatedSchedule(){var rows=(state.config.brightnessSchedule||[]).filter(function(x){return x.enabled!==false}).map(function(x){return{hour:Number(x.hour),minute:Number(x.minute),brightness:Number(x.brightness)}}),seen={};if(!rows.length)throw new Error("Cần bật ít nhất một mốc độ sáng.");rows.forEach(function(x){if(!Number.isInteger(x.hour)||x.hour<0||x.hour>23||!Number.isInteger(x.minute)||x.minute<0||x.minute>59||!Number.isInteger(x.brightness)||x.brightness<1||x.brightness>10)throw new Error("Lịch có giờ, phút hoặc độ sáng ngoài phạm vi.");var key=String(x.hour).padStart(2,"0")+":"+String(x.minute).padStart(2,"0");if(seen[key])throw new Error("Lịch bị trùng mốc "+key+".");seen[key]=true});return rows.sort(function(a,b){return a.hour*60+a.minute-(b.hour*60+b.minute)})}
  function schedulePayload(){return validatedSchedule().map(function(x){return String(x.hour).padStart(2,"0")+":"+String(x.minute).padStart(2,"0")+"="+x.brightness}).join("|")}
  function sendSchedule(){var payload,button=id("fp-send-schedule");if(!requireOnline())return;try{payload=schedulePayload()}catch(e){toast(e.message,"error");return}button.disabled=true;postCommand(state.station.scheduleTemplate,{payload:payload}).then(function(){toast(state.demoMode?"Thiết bị mô phỏng đã nhận lịch độ sáng: "+payload+".":"Gateway đã nhận lịch độ sáng: "+payload+".")}).catch(function(e){toast("Không gửi được lịch: "+e.message,"error")}).finally(function(){button.disabled=!deviceOnline()})}
  function sendBrightness(){if(!requireOnline())return;var value=Math.round(num(id("fp-brightness-now").value,7)),button=id("fp-send-brightness-now");button.disabled=true;postCommand(state.station.brightnessTemplate,{value:value}).then(function(){toast("Gateway đã nhận độ sáng "+value+"/10. Chờ telemetry xác nhận.");if(state.demoMode&&state.demoConnected)setTimeout(function(){var f=state.station.fields||{},payload={};payload[f.online]="ON";payload[f.brightness]=value;apply(payload);toast("Thiết bị mô phỏng đã áp dụng độ sáng "+value+"/10.")},650)}).catch(function(e){toast("Không gửi được độ sáng: "+e.message,"error")}).finally(function(){button.disabled=!deviceOnline()})}
  function apply(payload){state.payload=Object.assign({},state.payload,payload||{});state.lastSeenAt=Date.now();renderStation();renderSettingsState()}
  function snapshot(){return fetchTimeout(telemetryUrl(),{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error("Không đọc được telemetry");return r.json()}).then(function(p){var c=p&&p.c2;if(c&&c.payload)apply(c.payload)}).catch(function(e){log("Không tải được trạng thái thiết bị: "+e.message,"error")})}
  function connect(){if(typeof EventSource==="undefined")return;try{var source=new EventSource(streamUrl());state.stream=source;source.onopen=function(){state.streamConnected=true;snapshot()};source.onmessage=function(e){try{var d=JSON.parse(e.data);if(d.type==="telemetry")apply(d.payload)}catch(x){}};source.onerror=function(){source.close();state.stream=null;state.streamConnected=false;state.lastSeenAt=0;renderStation();clearTimeout(state.reconnect);state.reconnect=setTimeout(connect,3500)}}catch(e){state.streamConnected=false;state.lastSeenAt=0;renderStation();clearTimeout(state.reconnect);state.reconnect=setTimeout(connect,3500)}}
  function bind(){
    document.addEventListener("input",function(e){if(e.target.matches("[data-price-code]")){if(state.mode!=="manual")return;state.prices[e.target.getAttribute("data-price-code")]=Number(e.target.value);state.manualPrices=cloneValue(state.prices);renderLed();renderStation()}else if(e.target.id==="fp-brightness-now")id("fp-brightness-now-value").textContent=e.target.value;else if(e.target.matches("[data-schedule-key]")){var x=state.config.brightnessSchedule[Number(e.target.getAttribute("data-schedule-index"))],key=e.target.getAttribute("data-schedule-key");x[key]=key==="enabled"?e.target.checked:Number(e.target.value)}});
    document.addEventListener("click",function(e){
      var mode=e.target.closest("[data-price-mode]");
      if(mode){
        var next=mode.getAttribute("data-price-mode");
        if(next===state.mode)return;
        if(state.mode==="manual")state.manualPrices=cloneValue(state.prices);
        state.mode=next;
        if(next==="manual"){state.onlineFetchSeq=(state.onlineFetchSeq||0)+1;state.prices=cloneValue(state.manualPrices);id("fp-fetch-online").disabled=false;id("fp-fetch-online").textContent="Lấy lại giá Petrolimex"}
        else state.prices={};
        auditSoft("price_source",next==="online"?"price_mode_online":"price_mode_manual","success","Chọn nguồn giá "+(next==="online"?"Petrolimex và tự động lấy giá Vùng "+state.region:"nhập tay")+".",{mode:next,region:state.region});
        renderMode();
        if(next==="online")fetchOnline();
        return
      }
      if(e.target.id==="fp-send-brightness-now")sendBrightness()
    });
    id("fp-region").onchange=function(){state.region=Number(this.value)||1;state.prices={};auditSoft("price_source","price_region","success","Chọn Petrolimex Vùng "+state.region+"; hệ thống tự động lấy lại giá.",{region:state.region});renderMode();fetchOnline()};
    id("fp-fetch-online").onclick=fetchOnline;
    id("fp-source-link").href=(state.config.onlineSource||{}).homepage||"https://www.petrolimex.com.vn/";
    id("fp-open-confirm").onclick=openConfirm;id("fp-cancel-send").onclick=closeConfirm;id("fp-confirm-check").onchange=function(){id("fp-confirm-send").disabled=!this.checked};id("fp-confirm-send").onclick=sendPrices;id("fp-confirm-modal").onclick=function(e){if(e.target===this)closeConfirm()};id("fp-send-schedule").onclick=sendSchedule
  }
  function settingsSnapshot(){return{controller:cloneValue(state.config.ledSettings||{}),rows:(state.config.products||[]).map(function(p){return{code:p.code,enabled:p.displayEnabled!==false,brightness:Math.max(1,Math.min(10,Math.round(num(p.brightness,7))))}})}}
  function normalizeSettingsDraft(d){d=d||settingsSnapshot();d.controller.controllerAddress=Math.max(1,Math.min(255,Math.round(num(d.controller.controllerAddress,1))));d.controller.rfChannel=Math.max(1,Math.min(125,Math.round(num(d.controller.rfChannel,1))));d.controller.faceMode=d.controller.faceMode==="one"?"one":"two_same";d.controller.fanMode="continuous";d.controller.transport=d.controller.transport==="usb_uart"?"usb_uart":"2.4g_usb_uart";(d.rows||[]).forEach(function(r){r.enabled=r.enabled!==false;r.brightness=Math.max(1,Math.min(10,Math.round(num(r.brightness,7))))});return d}
  function readSettingsDraft(){if(!state.settingsDraft)state.settingsDraft=settingsSnapshot();var d=state.settingsDraft;d.controller.controllerAddress=id("fp-controller-address").value;d.controller.rfChannel=id("fp-rf-channel").value;d.controller.faceMode=id("fp-face-mode").value;d.controller.fanMode="continuous";d.controller.transport=id("fp-transport").value;document.querySelectorAll("[data-led-row-enabled]").forEach(function(n){var row=d.rows[Number(n.getAttribute("data-led-row-enabled"))];if(row)row.enabled=n.checked});document.querySelectorAll("[data-led-row-brightness]").forEach(function(n){var row=d.rows[Number(n.getAttribute("data-led-row-brightness"))];if(row)row.brightness=n.value});return normalizeSettingsDraft(d)}
  function applySettingsSnapshot(d){d=normalizeSettingsDraft(cloneValue(d));state.config.ledSettings=cloneValue(d.controller);state.config.ledSettings.fanMode="continuous";(state.config.products||[]).forEach(function(p){var row=d.rows.find(function(r){return r.code===p.code});if(row){p.displayEnabled=row.enabled;p.brightness=row.brightness}})}
  function ledRows(draft){var d=draft||settingsSnapshot();return(d.rows||[]).map(function(r){return{code:r.code,enabled:r.enabled!==false?1:0,brightness:Math.round(num(r.brightness,7))}})}
  function ledSettingsPayload(draft,v){var d=normalizeSettingsDraft(cloneValue(draft||settingsSnapshot())),s=d.controller;return(v?"VER="+v+"|":"")+"ADDR="+s.controllerAddress+"|CH="+s.rfChannel+"|FACE="+s.faceMode+"|FAN=continuous|LINK="+s.transport+"|ROWS="+ledRows(d).map(function(r){return r.code+":"+r.enabled+":"+r.brightness}).join(",")}
  function ledSettingsDescription(draft){var d=normalizeSettingsDraft(cloneValue(draft||settingsSnapshot())),s=d.controller,rows=ledRows(d).map(function(r){return r.code+" "+(r.enabled?"bật":"tắt")+" "+r.brightness+"/10"}).join("; ");return"địa chỉ "+s.controllerAddress+", kênh "+s.rfChannel+", "+(s.faceMode==="one"?"1 mặt":"2 mặt cùng nội dung")+", quạt liên tục, kết nối "+s.transport+"; các hàng: "+rows}
  function renderSettingsState(){var box=id("fp-settings-state");if(!box)return;var pending=state.pendingSettings,ack=text(read((state.station.fields||{}).settingsAckVersion),"");if(pending&&ack===String(pending.version)){pending.status="applied";saveOperationalState();box.dataset.state="applied";box.textContent="✓ Thiết bị đã ACK cấu hình "+pending.version}else if(pending){box.dataset.state="pending";box.textContent="Đang chờ thiết bị ACK cấu hình "+pending.version}else{box.dataset.state="saved";box.textContent=state.settingsSavedOnly?"Cấu hình đã lưu vào cơ sở dữ liệu · chưa gửi thiết bị":"Cài đặt đã lưu · chưa có lệnh đang chờ"}id("fp-settings-dirty").hidden=!state.settingsDirty}
  function renderLedSettings(){var d=state.settingsDraft||settingsSnapshot(),s=d.controller;id("fp-controller-address").value=s.controllerAddress;id("fp-rf-channel").value=s.rfChannel;id("fp-face-mode").value=s.faceMode;id("fp-fan-mode").value="continuous";id("fp-transport").value=s.transport;id("fp-row-settings").innerHTML=(d.rows||[]).map(function(r,i){var p=(state.config.products||[]).find(function(x){return x.code===r.code})||{label:r.code};return'<div class="fp-row-setting'+(r.enabled?'':' is-off')+'"><label class="fp-row-toggle"><input type="checkbox" data-led-row-enabled="'+i+'" '+(r.enabled?'checked':'')+'><span><strong>'+esc(p.label)+'</strong><small>'+(r.enabled?'Đang hiển thị':'Đang tắt')+'</small></span></label><label class="fp-row-brightness">Độ sáng riêng<input type="number" min="1" max="10" value="'+r.brightness+'" data-led-row-brightness="'+i+'"></label></div>'}).join("");renderSettingsState()}
  function saveSettingsSnapshot(draft,button,sent){var d=normalizeSettingsDraft(cloneValue(draft)),s=d.controller,a=state.config.audit||{},req=requestId("SET");if(button)button.disabled=true;return actorName().then(function(actor){return postMacro({macro:a.settingsSaveMacro||"fuel-settings-save",station_id:s.stationId||"default",controller_address:s.controllerAddress,rf_channel:s.rfChannel,face_mode:s.faceMode,fan_mode:"continuous",transport:s.transport,rows_json:JSON.stringify(ledRows(d)),request_id:req,actor:actor,detail:"Đã lưu cài đặt bảng LED: "+ledSettingsDescription(d)+".",payload_json:JSON.stringify(d)})}).then(function(){applySettingsSnapshot(d);state.settingsDirty=false;state.settingsSavedOnly=!sent;state.settingsDraft=settingsSnapshot();renderLed();renderLedSettings();return loadDbLogs()}).finally(function(){if(button)button.disabled=false})}
  function saveLedSettings(){var button=id("fp-save-settings"),d=readSettingsDraft();return saveSettingsSnapshot(d,button,false).then(function(){toast("Đã lưu bản nháp cài đặt vào cơ sở dữ liệu.")}).catch(function(e){toast("Không lưu được cài đặt: "+e.message,"error")})}
  function sendLedSettings(){if(!requireOnline())return;var button=id("fp-send-settings"),d=readSettingsDraft(),v=version(),payload=ledSettingsPayload(d,v);button.disabled=true;return postCommand(state.station.settingsTemplate,{payload:payload,version:v}).then(function(){state.pendingSettings={version:v,sentAt:Date.now(),status:"waiting"};saveOperationalState();return saveSettingsSnapshot(d,null,true)}).then(function(){toast("Gateway đã nhận cấu hình "+v+". Đang chờ thiết bị ACK.");renderSettingsState();demoAckSettings(v)}).catch(function(e){toast("Không gửi được cài đặt: "+e.message,"error")}).finally(function(){button.disabled=!deviceOnline()})}
  function setBoardEnabled(enabled){if(!requireOnline())return;var d=settingsSnapshot(),v=version();d.rows.forEach(function(r){r.enabled=!!enabled});var payload=ledSettingsPayload(d,v),detail=enabled?"Bật hiển thị toàn bảng LED":"Tắt hiển thị toàn bảng LED";id("fp-board-show").disabled=true;id("fp-board-off").disabled=true;return postCommand(state.station.settingsTemplate,{payload:payload,state:enabled?"ON":"OFF",version:v}).then(function(){state.pendingSettings={version:v,sentAt:Date.now(),status:"waiting"};saveOperationalState();return saveSettingsSnapshot(d,null,true)}).then(function(){toast("Gateway đã nhận lệnh: "+detail+". Chờ ACK thiết bị.");demoAckSettings(v)}).catch(function(e){toast(detail+" thất bại: "+e.message,"error")}).finally(function(){renderLed();renderSettingsState()})}
  function openSettings(){state.settingsDraft=settingsSnapshot();state.settingsDirty=false;renderLedSettings();id("fp-settings-page").hidden=false;document.body.classList.add("fp-settings-open");setTimeout(function(){id("fp-controller-address").focus()},0)}
  function closeSettings(force){if(state.settingsDirty&&!force&&!window.confirm("Bỏ các thay đổi cài đặt chưa lưu?"))return;state.settingsDraft=null;state.settingsDirty=false;id("fp-settings-page").hidden=true;document.body.classList.remove("fp-settings-open");renderSettingsState()}
  function loadDbSettings(){var a=state.config.audit||{},s=state.config.ledSettings;return postMacro({macro:a.settingsStateMacro||"fuel-settings-state",station_id:s.stationId||"default"}).then(function(rows){(rows||[]).forEach(function(r){if(r.row_type==="controller"){s.controllerAddress=Number(r.controller_address)||1;s.rfChannel=Number(r.rf_channel)||1;s.faceMode=r.face_mode==="one"?"one":"two_same";s.fanMode="continuous";s.transport=r.transport==="usb_uart"?"usb_uart":"2.4g_usb_uart"}else if(r.row_type==="row"){var p=(state.config.products||[]).find(function(x){return x.code===r.product_code});if(p){p.displayEnabled=Number(r.enabled)!==0;p.brightness=Number(r.brightness)||7}}});renderLed();renderSettingsState()}).catch(function(e){toast("Không đọc được cài đặt đã lưu: "+e.message,"error");renderLed()})}
  function clearDbLogs(){if(!window.confirm("Xóa toàn bộ nhật ký của trạm? Hành động này không thể hoàn tác."))return Promise.resolve();var a=state.config.audit||{},station=(state.config.ledSettings||{}).stationId||"default";return postMacro({macro:a.clearMacro||"fuel-audit-clear",station_id:station}).then(function(){state.logs=[];return dbAudit("system","clear_audit_logs","success","Đã xóa toàn bộ nhật ký cũ của trạm.",{station_id:station})}).then(function(){toast("Đã xóa log và ghi lại sự kiện xóa.")}).catch(function(e){toast("Không xóa được log: "+e.message,"error")})}
  function postCommand(template,values){var url=commandUrl(),action=template===state.station.commandTemplate?"send_prices":template===state.station.brightnessTemplate?"set_brightness":template===state.station.scheduleTemplate?"set_brightness_schedule":template===state.station.settingsTemplate?(values&&values.state==="ON"?"board_led_on":values&&values.state==="OFF"?"board_led_off":"send_led_settings"):"send_command",req=requestId("CMD"),cmdStarted=false;if(!deviceOnline())return Promise.reject(new Error("Thiết bị offline hoặc telemetry đã quá hạn"));if(!url||!template)return Promise.reject(new Error("Thiếu Device key hoặc mẫu lệnh."));return dbAudit("control",action,"pending",commandAuditDetail(action,values,"pending"),values,req).catch(function(e){throw new Error("Không ghi được nhật ký bắt buộc; lệnh chưa được gửi: "+e.message)}).then(function(){cmdStarted=true;return resolveTemplate(template,values)}).then(function(cmd){return fetchTimeout(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cmd:cmd})}).then(function(r){if(!r.ok)throw new Error("Gateway từ chối lệnh");return dbAudit("control",action,"success",commandAuditDetail(action,values,"success"),values,req).catch(function(e){toast("Gateway đã nhận lệnh nhưng log kết quả chưa lưu: "+e.message,"error")}).then(function(){return cmd})})}).catch(function(e){if(!cmdStarted||/^Không ghi được nhật ký bắt buộc/.test(e.message))throw e;return dbAudit("control",action,"error",commandAuditDetail(action,values,"error",e.message),values,req).catch(function(){return null}).then(function(){throw e})})}
  function loadDbLogs(){var a=state.config.audit||{};return postMacro({macro:a.listMacro||"fuel-audit-list",category:state.logFilter||"",limit:150}).then(function(rows){state.logs=(rows||[]).filter(function(x){return x&&x.id!=null}).map(function(x){return{time:new Date(Number(x.ts)||Date.now()),message:String(x.detail||x.action||""),type:x.status==="error"?"error":x.status==="warning"?"warn":x.status==="success"?"success":"info",status:String(x.status||"success"),category:String(x.category||"system"),action:String(x.action||""),requestId:String(x.request_id||"")}});renderLog();return rows}).catch(function(e){state.dbAvailable=false;renderLog();throw e})}
  function renderLog(){var box=id("fp-log");if(!box)return;var rows=(state.logs||[]).filter(function(x){return!state.logFilter||x.category===state.logFilter}),statusLabel={pending:"ĐANG GỬI",success:"THÀNH CÔNG",error:"LỖI",warning:"CẢNH BÁO"};box.innerHTML=rows.length?rows.map(function(x){var status=x.status||((x.type==="error")?"error":x.type==="warn"?"warning":x.type==="success"?"success":"success");return'<div class="fp-log-row" data-type="'+esc(x.type)+'"><time>'+x.time.toLocaleString("vi-VN")+'</time><span><b>'+esc(x.category==="control"?"ĐIỀU KHIỂN":x.category==="setting"?"CÀI ĐẶT":x.category==="price_source"?"NGUỒN GIÁ":"HỆ THỐNG")+'</b><span class="fp-log-status" data-status="'+esc(status)+'">'+esc(statusLabel[status]||status.toUpperCase())+'</span><strong class="fp-log-action">'+esc(auditActionLabel(x.action))+'</strong><span class="fp-log-detail">'+esc(x.message)+'</span>'+(x.requestId?'<small>Mã yêu cầu: '+esc(x.requestId)+'</small>':'')+'</span></div>'}).join(""):'<div class="fp-log-empty">Chưa có sự kiện phù hợp.</div>'}
  function initExtended(){if(!state.config||!state.station)return;ensureLedSettings();state.config.ledSettings.fanMode="continuous";id("fp-save-settings").onclick=saveLedSettings;id("fp-send-settings").onclick=sendLedSettings;id("fp-open-settings").onclick=openSettings;id("fp-close-settings").onclick=function(){closeSettings(false)};id("fp-board-show").onclick=function(){setBoardEnabled(true)};id("fp-board-off").onclick=function(){setBoardEnabled(false)};id("fp-settings-page").addEventListener("input",function(e){if(!e.target.matches("#fp-controller-address,#fp-rf-channel,#fp-face-mode,#fp-transport,[data-led-row-enabled],[data-led-row-brightness]"))return;readSettingsDraft();state.settingsDirty=true;var card=e.target.closest(".fp-row-setting"),status=card&&card.querySelector("small");if(card&&e.target.matches("[data-led-row-enabled]")){card.classList.toggle("is-off",!e.target.checked);if(status)status.textContent=e.target.checked?"Đang hiển thị":"Đang tắt"}renderSettingsState()});id("fp-settings-page").onclick=function(e){if(e.target===this)closeSettings(false)};document.addEventListener("keydown",function(e){if(e.key==="Escape"&&!id("fp-settings-page").hidden)closeSettings(false)});id("fp-log-filter").value=state.logFilter;id("fp-log-filter").onchange=function(){state.logFilter=this.value;loadDbLogs().catch(function(){})};id("fp-clear-log").onclick=clearDbLogs;loadDbSettings().then(function(){return loadDbLogs()}).catch(function(){})}
  function theme(){var p=id("theme-picker"),t=id("theme-picker-toggle"),m=id("theme-picker-menu");function open(v){p.classList.toggle("is-open",v);t.setAttribute("aria-expanded",v?"true":"false")}t.onclick=function(e){e.stopPropagation();open(!p.classList.contains("is-open"))};m.onclick=function(e){var b=e.target.closest("[data-theme-option]");if(!b)return;var v=b.getAttribute("data-theme-option");document.documentElement.setAttribute("data-theme",v);try{localStorage.setItem("sample-dashboard-theme",v)}catch(x){}open(false)};document.addEventListener("click",function(e){if(!p.contains(e.target))open(false)})}
  function init(){var c=parse();if(!c)return;c.products=Array.isArray(c.products)?c.products:[];c.brightnessSchedule=Array.isArray(c.brightnessSchedule)?c.brightnessSchedule:[];state.config=c;state.station=c.station||(Array.isArray(c.stations)&&c.stations[0])||{};state.mode=c.priceMode==="online"?"online":"manual";state.region=Number(c.region)===2?2:1;c.products.forEach(function(p){state.prices[p.code]=Math.round(num(p.manualPrice,0))});initOperationalState();if(state.mode==="online")state.prices={};id("fp-title").textContent=text(c.title,"Quản lý bảng giá xăng dầu");id("fp-subtitle").textContent=text(c.subtitle,"");id("fp-region").value=String(state.region);function clock(){id("fp-clock").textContent=new Date().toLocaleTimeString("vi-VN")}clock();setInterval(clock,1000);loadLogs();bind();theme();log("Đã mở phiên quản lý "+text(state.station.name,"trạm xăng")+".");render();if(state.mode==="online")fetchOnline();if(state.demoMode)startDemo();else snapshot().finally(connect)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(initExtended,0)},{once:true});else setTimeout(initExtended,0);
})();
