(function(){
  "use strict";
  var state={config:null,meters:[],sessions:Object.create(null),historyMinutes:1440};
  function id(v){return document.getElementById(v)}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function text(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}
  function num(v){if(v===null||v===undefined||v==="")return null;var n=Number(v);return Number.isFinite(n)?n:null}
  function hydrate(raw){var c=window.ROSA_SIMULATOR_CONTEXT||{};return String(raw||"").replace(/<<sessionid>>/gi,text(c.sessionId,"IO123abcd@simulate")).replace(/<<syncid>>/gi,text(c.syncId,"SIM_SYNC"))}
  function parse(){try{return JSON.parse(hydrate(id("factory-energy-config").textContent))}catch(e){return null}}
  function key(v){return String(v||"").toLowerCase()}
  function sessionState(sessionId){if(!state.sessions[sessionId])state.sessions[sessionId]={values:Object.create(null),rows:[],connection:"connecting",lastSeen:0,source:null,reconnect:0};return state.sessions[sessionId]}
  function read(meter,fieldKey){var field=meter.fields[fieldKey],s=sessionState(meter.sessionId);return s.values[key(field)]}
  function setValues(sessionId,payload){var s=sessionState(sessionId);if(!payload||typeof payload!=="object")return;Object.keys(payload).forEach(function(field){s.values[key(field)]=payload[field]})}
  function normalizeMeter(raw,index){raw=raw||{};var f=raw.fields||{};return{name:text(raw.name,"Khu vực "+(index+1)),description:text(raw.description,""),sessionId:text(raw.sessionId,""),accent:text(raw.accent,["#2563eb","#8b5cf6","#14b8a6","#f59e0b"][index%4]),fields:{voltage1:text(f.voltage1,""),voltage2:text(f.voltage2,""),voltage3:text(f.voltage3,""),current1:text(f.current1,""),current2:text(f.current2,""),current3:text(f.current3,""),power:text(f.power,""),energyToday:text(f.energyToday,""),powerFactor:text(f.powerFactor,""),frequency:text(f.frequency,"")}}}
  function fieldsForSession(sessionId){var out=[];state.meters.filter(function(m){return m.sessionId===sessionId}).forEach(function(m){Object.keys(m.fields).forEach(function(k){if(m.fields[k]&&out.indexOf(m.fields[k])<0)out.push(m.fields[k])})});return out}
  function powerFieldsForSession(sessionId){return state.meters.filter(function(m){return m.sessionId===sessionId&&m.fields.power}).map(function(m){return m.fields.power}).filter(function(v,i,a){return a.indexOf(v)===i})}
  function sessions(){return Object.keys(state.sessions)}
  function apiUrl(sessionId,type){if(!sessionId||!state.config.syncId)return"";var q=new URLSearchParams(),now=Date.now(),fields=type==="iotimeseries"?powerFieldsForSession(sessionId):fieldsForSession(sessionId);q.set("fields",fields.join(","));if(type==="iotimeseries"){q.set("from",String(now-state.historyMinutes*60000));q.set("to",String(now))}return"/api/"+encodeURIComponent(sessionId)+"/"+encodeURIComponent(state.config.syncId)+"/"+type+"?"+q}
  function streamUrl(sessionId){var q=new URLSearchParams();q.set("fields",fieldsForSession(sessionId).join(","));return"/api/"+encodeURIComponent(sessionId)+"/stream?"+q}
  function values(meter,names){return names.map(function(n){return num(read(meter,n))})}
  function imbalance(list){var valid=list.filter(function(v){return v!==null});if(valid.length<2)return null;var avg=valid.reduce(function(s,v){return s+v},0)/valid.length;if(avg<=0)return 0;return(Math.max.apply(null,valid)-Math.min.apply(null,valid))/avg*100}
  function assessment(meter){var t=state.config.thresholds,volts=values(meter,["voltage1","voltage2","voltage3"]),currents=values(meter,["current1","current2","current3"]),power=num(read(meter,"power")),energy=num(read(meter,"energyToday")),pf=num(read(meter,"powerFactor")),frequency=num(read(meter,"frequency")),currentImbalance=imbalance(currents),issues=[],hasData=volts.concat(currents,[power,energy,pf,frequency]).some(function(v){return v!==null}),connection=sessionState(meter.sessionId).connection;if(connection==="offline")issues.push("Mất kết nối");if(volts.some(function(v){return v!==null&&(v<t.voltageLow||v>t.voltageHigh)}))issues.push("Điện áp ngoài ngưỡng");if(currentImbalance!==null&&currentImbalance>t.currentImbalanceWarn)issues.push("Dòng điện lệch pha "+currentImbalance.toFixed(1)+"%");if(power!==null&&power>t.powerWarnKw)issues.push("Công suất cao");if(pf!==null&&pf<t.powerFactorMin)issues.push("Hệ số công suất thấp");if(frequency!==null&&(frequency<t.frequencyLow||frequency>t.frequencyHigh))issues.push("Tần số ngoài ngưỡng");return{volts:volts,currents:currents,power:power,energy:energy,pf:pf,frequency:frequency,imbalance:currentImbalance,issues:issues,danger:issues.length>0,hasData:hasData,connection:connection}}
  function fmt(v,digits,unit){return v===null?"--":v.toLocaleString("vi-VN",{minimumFractionDigits:digits,maximumFractionDigits:digits})+(unit||"")}
  function money(v){try{return new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(Math.max(0,v||0))}catch(e){return Math.round(v||0).toLocaleString("vi-VN")+" ₫"}}
  function renderKpis(){var checks=state.meters.map(assessment),powers=checks.map(function(a){return a.power}).filter(function(v){return v!==null}),energies=checks.map(function(a){return a.energy}).filter(function(v){return v!==null}),pfs=checks.map(function(a){return a.pf}).filter(function(v){return v!==null}),totalPower=powers.reduce(function(s,v){return s+v},0),totalEnergy=energies.reduce(function(s,v){return s+v},0),avgPf=pfs.length?pfs.reduce(function(s,v){return s+v},0)/pfs.length:null,danger=checks.filter(function(a){return a.danger}).length;id("fe-kpis").innerHTML=[
    ["Tổng công suất",powers.length?fmt(totalPower,1," kW"):"--",danger?danger+" khu vực cần kiểm tra":"Phụ tải tức thời",totalPower>state.config.thresholds.powerWarnKw*state.meters.length],
    ["Điện năng hôm nay",energies.length?fmt(totalEnergy,1," kWh"):"--",energies.length+" khu vực có dữ liệu",false],
    ["Chi phí dự kiến",energies.length?money(totalEnergy*state.config.electricityRate):"--",state.config.electricityRate.toLocaleString("vi-VN")+" ₫/kWh",false],
    ["Hệ số công suất TB",avgPf===null?"--":avgPf.toFixed(2),avgPf!==null&&avgPf<state.config.thresholds.powerFactorMin?"Cần bù công suất":"Mục tiêu ≥ "+state.config.thresholds.powerFactorMin,avgPf!==null&&avgPf<state.config.thresholds.powerFactorMin]
  ].map(function(k){return'<article class="fe-kpi"><span>'+k[0]+'</span><strong data-state="'+(k[3]?'danger':'normal')+'">'+k[1]+'</strong><small>'+k[2]+'</small></article>'}).join("")}
  function renderLoads(){var rows=state.meters.map(function(m){return{meter:m,power:num(read(m,"power"))}}),total=rows.reduce(function(s,r){return s+(r.power||0)},0);id("fe-load-list").innerHTML=rows.map(function(r){var pct=total>0&&r.power!==null?r.power/total*100:0;return'<div class="fe-load-row" style="--accent:'+esc(r.meter.accent)+'"><div><span>'+esc(r.meter.name)+'</span><strong>'+fmt(r.power,1," kW")+'</strong></div><span class="fe-small">'+(r.power===null?'--':pct.toFixed(0)+"%")+'</span><div class="fe-load-track"><i style="width:'+pct+'%"></i></div></div>'}).join("");id("fe-load-note").textContent=total?"Tổng "+fmt(total,1," kW"):"Chưa có dữ liệu"}
  function phaseCell(v,kind){var t=state.config.thresholds,danger=v!==null&&kind==="voltage"&&(v<t.voltageLow||v>t.voltageHigh);return'<strong data-state="'+(danger?'danger':'normal')+'">'+fmt(v,kind==="voltage"?1:2,kind==="voltage"?" V":" A")+'</strong>'}
  function meterHtml(m,index){var a=assessment(m),s=sessionState(m.sessionId),status=!a.hasData?"CHỜ DỮ LIỆU":a.danger?"CẦN KIỂM TRA":"ỔN ĐỊNH";return'<article class="fe-meter" data-state="'+(a.danger?'danger':'normal')+'" style="--accent:'+esc(m.accent)+'"><div class="fe-meter-head"><div class="fe-meter-title"><i class="fe-status-dot" data-state="'+(a.danger?'danger':a.hasData?'normal':'pending')+'"></i><div><h3>'+esc(m.name)+'</h3><p>'+esc(m.description)+'</p></div></div><span class="fe-state" data-state="'+(a.danger?'danger':'normal')+'">'+status+'</span></div><div class="fe-phase-table"><span class="head"></span><span class="head">L1</span><span class="head">L2</span><span class="head">L3</span><span class="label">Điện áp</span>'+a.volts.map(function(v){return phaseCell(v,"voltage")}).join("")+'<span class="label">Dòng điện</span>'+a.currents.map(function(v){return phaseCell(v,"current")}).join("")+'</div><div class="fe-meter-kpis"><div class="fe-meter-kpi"><span>Công suất</span><strong data-state="'+(a.power!==null&&a.power>state.config.thresholds.powerWarnKw?'danger':'normal')+'">'+fmt(a.power,1," kW")+'</strong></div><div class="fe-meter-kpi"><span>Điện năng ngày</span><strong>'+fmt(a.energy,1," kWh")+'</strong></div><div class="fe-meter-kpi"><span>Hệ số CS</span><strong data-state="'+(a.pf!==null&&a.pf<state.config.thresholds.powerFactorMin?'danger':'normal')+'">'+fmt(a.pf,2,"")+'</strong></div><div class="fe-meter-kpi"><span>Tần số</span><strong data-state="'+(a.frequency!==null&&(a.frequency<state.config.thresholds.frequencyLow||a.frequency>state.config.thresholds.frequencyHigh)?'danger':'normal')+'">'+fmt(a.frequency,2," Hz")+'</strong></div></div><div class="fe-meter-foot"><span>Lệch dòng: '+fmt(a.imbalance,1,"%")+'</span><span>'+(s.connection==="online"?"Trực tuyến":s.connection==="offline"?"Ngoại tuyến":"Đang kết nối")+'</span></div></article>'}
  function renderMeters(){var checks=state.meters.map(assessment),danger=checks.filter(function(a){return a.danger}).length;id("fe-meters").innerHTML=state.meters.length?state.meters.map(meterHtml).join(""):'<article class="fe-panel">Chưa có khu vực điện nào được cấu hình.</article>';id("fe-meter-summary").textContent=danger?danger+" khu vực cần kiểm tra":checks.some(function(a){return a.hasData})?"Các khu vực đang trong giới hạn":"Đang chờ dữ liệu"}
  function meterRows(m){return sessionState(m.sessionId).rows.filter(function(r){return key(r.field)===key(m.fields.power)})}
  function renderChart(){var sets=state.meters.map(function(m){return{meter:m,rows:meterRows(m)}}),all=[];sets.forEach(function(s){all=all.concat(s.rows)});var xMin=all.length?Math.min.apply(null,all.map(function(r){return r.ts})):0,xMax=all.length?Math.max.apply(null,all.map(function(r){return r.ts})):1,yMax=all.length?Math.max.apply(null,all.map(function(r){return r.value})):1;if(xMax===xMin)xMax=xMin+1;if(yMax<=0)yMax=1;id("fe-chart-paths").innerHTML=sets.map(function(s){var d=s.rows.map(function(r,i){var x=24+(r.ts-xMin)/(xMax-xMin)*632,y=182-r.value/yMax*140;return(i?"L":"M")+x.toFixed(1)+" "+y.toFixed(1)}).join(" ");return'<path d="'+d+'" stroke="'+esc(s.meter.accent)+'"/>'}).join("");id("fe-chart-legend").innerHTML=sets.map(function(s){return'<span><i style="background:'+esc(s.meter.accent)+'"></i>'+esc(s.meter.name)+'</span>'}).join("")}
  function renderStatus(){var active=sessions().filter(function(s){return sessionState(s).connection==="online"}).length,offline=sessions().filter(function(s){return sessionState(s).connection==="offline"}).length,dot=id("fe-live-dot"),label=id("fe-live-text"),messages=[];state.meters.forEach(function(m){var a=assessment(m);if(a.issues.length)messages.push(m.name+": "+a.issues.join(", "))});dot.setAttribute("data-state",active?"online":offline?"offline":"connecting");label.textContent=active?active+"/"+sessions().length+" thiết bị trực tuyến":offline?"Mất kết nối":"Đang kết nối";var alert=id("fe-alert");alert.hidden=!messages.length;alert.textContent=messages.length?"⚠ "+messages.join("  •  "):""}
  function render(){if(!state.config)return;renderKpis();renderLoads();renderMeters();renderChart();renderStatus()}
  function applyRows(sessionId,rows){var s=sessionState(sessionId),wanted=powerFieldsForSession(sessionId).map(key);(rows||[]).forEach(function(r){if(wanted.indexOf(key(r.field))<0)return;var row={field:r.field,ts:Number(r.ts),value:Number(r.value)};if(Number.isFinite(row.ts)&&Number.isFinite(row.value))s.rows.push(row)});var cutoff=Date.now()-state.historyMinutes*60000;s.rows=s.rows.filter(function(r){return r.ts>=cutoff}).slice(-720)}
  function fetchJson(url){if(!url)return Promise.resolve(null);return fetch(url,{cache:"no-store"}).then(function(r){return r.ok?r.json():null}).catch(function(){return null})}
  function bootstrap(sessionId){return Promise.all([fetchJson(apiUrl(sessionId,"iotelemetry")),fetchJson(apiUrl(sessionId,"iotimeseries"))]).then(function(parts){var tele=parts[0]&&parts[0].c2,hist=parts[1]&&parts[1].c2,s=sessionState(sessionId);setValues(sessionId,tele&&tele.payload||{});s.lastSeen=Number(tele&&tele.serverTime)||0;s.rows=[];applyRows(sessionId,hist&&hist.rows||[]);render()})}
  function connect(sessionId){var s=sessionState(sessionId),url=streamUrl(sessionId);if(!url||typeof EventSource==="undefined"){s.connection="offline";renderStatus();return}try{var source=new EventSource(url);s.source=source;source.onopen=function(){s.connection="online";render()};source.onmessage=function(e){try{var d=JSON.parse(e.data);s.connection="online";if(d.type==="telemetry"&&d.payload){setValues(sessionId,d.payload);s.lastSeen=Number(d.serverTime)||Date.now()}else if(d.type==="timeseries")applyRows(sessionId,d.rows);render()}catch(x){}};source.onerror=function(){source.close();s.source=null;s.connection="offline";render();clearTimeout(s.reconnect);s.reconnect=setTimeout(function(){connect(sessionId)},3000)}}catch(e){s.connection="offline";render()}}
  function reloadHistory(){sessions().forEach(function(sessionId){sessionState(sessionId).rows=[]});Promise.all(sessions().map(function(sessionId){return fetchJson(apiUrl(sessionId,"iotimeseries")).then(function(p){applyRows(sessionId,p&&p.c2&&p.c2.rows||[])})})).then(render)}
  function theme(){var p=id("theme-picker"),t=id("theme-picker-toggle"),m=id("theme-picker-menu");function open(v){p.classList.toggle("is-open",v);t.setAttribute("aria-expanded",v?"true":"false")}t.onclick=function(e){e.stopPropagation();open(!p.classList.contains("is-open"))};m.onclick=function(e){var b=e.target.closest("[data-theme-option]");if(!b)return;var v=b.getAttribute("data-theme-option");document.documentElement.setAttribute("data-theme",v);try{localStorage.setItem("sample-dashboard-theme",v)}catch(x){}m.querySelectorAll("button").forEach(function(n){n.classList.toggle("is-active",n===b)});open(false)};document.addEventListener("click",function(e){if(!p.contains(e.target))open(false)})}
  function init(){var c=parse();if(!c){id("fe-meter-summary").textContent="Cấu hình template không hợp lệ.";return}c.thresholds=c.thresholds||{};c.electricityRate=Number(c.electricityRate)||0;state.config=c;state.historyMinutes=Number(c.historyMinutes)||1440;state.meters=(Array.isArray(c.meters)?c.meters:[]).map(normalizeMeter).filter(function(m){return m.sessionId});state.meters.forEach(function(m){sessionState(m.sessionId)});id("fe-title").textContent=text(c.title,"Giám sát điện năng nhà xưởng");id("fe-subtitle").textContent=text(c.subtitle,"");id("fe-range").value=String(state.historyMinutes);id("fe-range").onchange=function(){state.historyMinutes=Number(this.value)||1440;state.config.historyMinutes=state.historyMinutes;reloadHistory()};function clock(){id("fe-clock").textContent=new Date().toLocaleTimeString("vi-VN")}clock();setInterval(clock,1000);theme();render();sessions().forEach(function(sessionId){bootstrap(sessionId).finally(function(){connect(sessionId)})})}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
