(function(){
  "use strict";
  var FIELD_LABELS={voltageL1:"Điện áp pha L1",voltageL2:"Điện áp pha L2",voltageL3:"Điện áp pha L3",currentL1:"Dòng điện pha L1",currentL2:"Dòng điện pha L2",currentL3:"Dòng điện pha L3",powerKw:"Công suất tác dụng",energyTodayKwh:"Điện năng hôm nay",powerFactor:"Hệ số công suất",frequencyHz:"Tần số"};
  function fields(prefix){return{voltageL1:prefix+"_voltage_l1",voltageL2:prefix+"_voltage_l2",voltageL3:prefix+"_voltage_l3",currentL1:prefix+"_current_l1",currentL2:prefix+"_current_l2",currentL3:prefix+"_current_l3",powerKw:prefix+"_power_kw",energyTodayKwh:prefix+"_energy_today_kwh",powerFactor:prefix+"_power_factor",frequencyHz:prefix+"_frequency_hz"}}
  function meter(name,description,prefix,accent){return{name:name,description:description,sessionId:"<<sessionid>>",accent:accent,fields:fields(prefix)}}
  var DEFAULT={locale:"vi",title:"Giám sát điện năng nhà xưởng",subtitle:"Phụ tải, chất lượng điện và chi phí theo từng khu vực",syncId:"<<syncid>>",historyMinutes:1440,electricityRate:2100,thresholds:{voltageLow:205,voltageHigh:235,currentImbalanceWarn:12,powerFactorMin:0.85,frequencyLow:49,frequencyHigh:51,powerWarnKw:55},meters:[meter("Xưởng ép nhựa","Tủ điện MSB-01","press","#2563eb"),meter("Xưởng đóng gói","Tủ điện DB-02","pack","#8b5cf6"),meter("Hệ thống phụ trợ","Khí nén, bơm và HVAC","utility","#14b8a6")]};
  var state={config:clone(DEFAULT),context:{}};
  function clone(v){return JSON.parse(JSON.stringify(v==null?{}:v))}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function safe(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}
  function num(v,f){var n=Number(v);return Number.isFinite(n)?n:Number(f||0)}
  function input(label,attr,key,value,type,step){return'<label>'+esc(label)+'<input '+attr+'="'+key+'" type="'+(type||"text")+'"'+(step?' step="'+step+'"':'')+' value="'+esc(value)+'"></label>'}
  function meterHtml(m,index){return'<article class="item-card" data-meter="'+index+'"><div class="item-top"><div><h3>'+esc(m.name||("Khu vực "+(index+1)))+'</h3><div class="status">'+esc(m.description||"Đồng hồ điện 3 pha")+'</div></div><div><button class="secondary" data-action="clone" data-index="'+index+'">Nhân bản</button> <button class="danger" data-action="delete" data-index="'+index+'">Xóa</button></div></div><div class="grid">'+input("Tên khu vực","data-meter-key","name",m.name)+input("Mô tả / tủ điện","data-meter-key","description",m.description)+input("Device key","data-meter-key","sessionId",m.sessionId)+input("Màu nhận diện","data-meter-key","accent",m.accent,"color")+'</div><div class="grid">'+Object.keys(FIELD_LABELS).map(function(k){return input(FIELD_LABELS[k],"data-field-key",k,(m.fields||{})[k])}).join("")+'</div></article>'}
  function render(){var c=state.config,meters=Array.isArray(c.meters)?c.meters:[],t=c.thresholds||{};document.body.innerHTML='<main class="shell"><header class="head"><div><h1>Cài đặt giám sát điện năng nhà xưởng</h1><div class="status">Cấu hình đồng hồ 3 pha, giá điện, ngưỡng chất lượng điện và từng khu vực.</div></div><div class="badge">'+meters.length+' khu vực</div></header><section class="panel"><h2>Thông tin chung</h2><div class="grid">'+input("Tên dashboard","data-general","title",c.title)+input("AccountID","data-general","syncId",c.syncId)+input("Lịch sử mặc định (phút)","data-general","historyMinutes",c.historyMinutes,"number")+input("Đơn giá điện (đ/kWh)","data-general","electricityRate",c.electricityRate,"number")+'<label class="full">Mô tả<input data-general="subtitle" value="'+esc(c.subtitle)+'"></label></div></section><section class="panel"><h2>Ngưỡng vận hành</h2><div class="grid">'+input("Điện áp thấp (V)","data-threshold","voltageLow",t.voltageLow,"number","0.1")+input("Điện áp cao (V)","data-threshold","voltageHigh",t.voltageHigh,"number","0.1")+input("Mất cân bằng dòng cảnh báo (%)","data-threshold","currentImbalanceWarn",t.currentImbalanceWarn,"number","0.1")+input("Hệ số công suất tối thiểu","data-threshold","powerFactorMin",t.powerFactorMin,"number","0.01")+input("Tần số thấp (Hz)","data-threshold","frequencyLow",t.frequencyLow,"number","0.1")+input("Tần số cao (Hz)","data-threshold","frequencyHigh",t.frequencyHigh,"number","0.1")+input("Công suất cảnh báo mỗi khu (kW)","data-threshold","powerWarnKw",t.powerWarnKw,"number","0.1")+'</div></section><section class="panel"><div class="toolbar"><h2>Khu vực / đồng hồ điện</h2><button data-action="add">+ Thêm khu vực</button></div><div class="item-list">'+meters.map(meterHtml).join("")+'</div></section></main>';DashboardSetupBridge.resize()}
  function read(){var c=state.config;document.querySelectorAll("[data-general]").forEach(function(n){var k=n.getAttribute("data-general");c[k]=(k==="historyMinutes")?Math.max(15,num(n.value,1440)):(k==="electricityRate")?Math.max(0,num(n.value,2100)):safe(n.value,c[k])});c.thresholds=c.thresholds||{};document.querySelectorAll("[data-threshold]").forEach(function(n){c.thresholds[n.getAttribute("data-threshold")]=num(n.value,c.thresholds[n.getAttribute("data-threshold")])});document.querySelectorAll("[data-meter]").forEach(function(card){var m=c.meters[Number(card.getAttribute("data-meter"))];m.fields=m.fields||{};card.querySelectorAll("[data-meter-key]").forEach(function(n){m[n.getAttribute("data-meter-key")]=safe(n.value,m[n.getAttribute("data-meter-key")])});card.querySelectorAll("[data-field-key]").forEach(function(n){m.fields[n.getAttribute("data-field-key")]=safe(n.value,m.fields[n.getAttribute("data-field-key")])})})}
  function initialize(payload){state.context=clone(payload&&payload.context||{});var incoming=payload&&payload.config;state.config=clone(incoming&&Object.keys(incoming).length?incoming:DEFAULT);state.config.meters=Array.isArray(state.config.meters)?state.config.meters:clone(DEFAULT.meters);if(!state.config.syncId)state.config.syncId=state.context.syncId||"";state.config.meters.forEach(function(m){if(!m.sessionId)m.sessionId=state.context.sessionId||""});render()}
  function collect(){read();var c=state.config,t=c.thresholds;if(!c.title)throw new Error("Hãy nhập tên dashboard.");if(!c.meters||!c.meters.length)throw new Error("Cần ít nhất một khu vực đo điện.");if(t.voltageLow>=t.voltageHigh)throw new Error("Ngưỡng điện áp thấp phải nhỏ hơn ngưỡng cao.");if(t.frequencyLow>=t.frequencyHigh)throw new Error("Ngưỡng tần số thấp phải nhỏ hơn ngưỡng cao.");if(t.powerFactorMin<0||t.powerFactorMin>1)throw new Error("Hệ số công suất phải nằm trong khoảng 0 đến 1.");c.meters.forEach(function(m){if(!m.name||!m.sessionId||!m.fields||!m.fields.powerKw)throw new Error("Mỗi khu vực cần tên, Device key và field công suất.")});return clone(c)}
  document.addEventListener("click",function(e){var b=e.target.closest("[data-action]");if(!b)return;e.preventDefault();read();var action=b.getAttribute("data-action"),index=Number(b.getAttribute("data-index"));if(action==="add"){var n=state.config.meters.length,prefix="area"+(n+1);state.config.meters.push(meter("Khu vực "+(n+1),"Đồng hồ điện 3 pha",prefix,"#f59e0b"))}else if(action==="clone"){var copy=clone(state.config.meters[index]);copy.name=safe(copy.name,"Khu vực")+" copy";state.config.meters.splice(index+1,0,copy)}else if(action==="delete"){if(state.config.meters.length<=1){DashboardSetupBridge.error("Cần giữ ít nhất một khu vực đo điện.");return}state.config.meters.splice(index,1)}render()});
  render();DashboardSetupBridge.start({onInit:initialize,onCollect:collect});
})();
