(function(){"use strict";
  var DEFAULT={locale:"vi",title:"Điện nước nhà trọ",subtitle:"Theo dõi chỉ số, tiền phòng và thanh toán theo thời gian thực",syncId:"<<syncid>>",electricRate:3500,waterRate:15000,serviceFee:100000,dueDay:5,rooms:[roomFactory(0,"P101"),roomFactory(1,"P102"),roomFactory(100,"P201"),roomFactory(101,"P202")]};
  DEFAULT.rooms[0].tenant="Nguyễn Văn An";DEFAULT.rooms[0].rent=2500000;DEFAULT.rooms[0].electricStart=1250;DEFAULT.rooms[0].waterStart=86;
  DEFAULT.rooms[1].tenant="Trần Minh Châu";DEFAULT.rooms[1].rent=2800000;DEFAULT.rooms[1].electricStart=980;DEFAULT.rooms[1].waterStart=63;
  DEFAULT.rooms[2].tenant="Lê Hoàng Nam";DEFAULT.rooms[2].rent=2600000;DEFAULT.rooms[2].electricStart=1440;DEFAULT.rooms[2].waterStart=102;
  DEFAULT.rooms[3].tenant="Phạm Thu Hà";DEFAULT.rooms[3].rent=3000000;DEFAULT.rooms[3].electricStart=720;DEFAULT.rooms[3].waterStart=48;
  var state={config:clone(DEFAULT),context:{}};
  function clone(v){return JSON.parse(JSON.stringify(v==null?{}:v))}function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function safe(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}function num(v,f){var n=Number(v);return Number.isFinite(n)?n:Number(f||0)}
  function roomFactory(index,code){var id=String(code||("P"+(index+1))).toLowerCase();var output="O"+(101+index);return{code:code||("P"+(index+1)),tenant:"Khách thuê "+(index+1),sessionId:"<<sessionid>>",rent:2500000,electricStart:0,waterStart:0,fields:{electricity:id+"_electricity_kwh",water:id+"_water_m3",power:id+"_power_w",paid:id+"_paid",relay:output},commands:{on:"D1"+output,off:"D2"+output}}}
  function input(label,key,value,type){return'<label>'+esc(label)+'<input data-key="'+esc(key)+'" type="'+(type||"text")+'" value="'+esc(value)+'"></label>'}
  function render(){var c=state.config,rooms=Array.isArray(c.rooms)?c.rooms:[];document.body.innerHTML='<main class="shell"><header class="head"><div><h1>Cài đặt điện nước nhà trọ</h1><div class="status">Thiết lập đơn giá, chỉ số đầu tháng và ánh xạ thiết bị từng phòng.</div></div><div class="badge">'+rooms.length+' phòng</div></header><section class="panel"><h2>Thông tin chung</h2><div class="grid">'+input("Tên dashboard","title",c.title)+input("AccountID dùng chung","syncId",c.syncId)+input("Ngày hạn thu","dueDay",c.dueDay,"number")+input("Đơn giá điện (₫/kWh)","electricRate",c.electricRate,"number")+input("Đơn giá nước (₫/m³)","waterRate",c.waterRate,"number")+input("Phí dịch vụ mỗi phòng (₫)","serviceFee",c.serviceFee,"number")+'<label class="full">Mô tả<input data-key="subtitle" value="'+esc(c.subtitle)+'"></label></div></section><section class="panel"><div class="toolbar"><h2>Danh sách phòng</h2><button type="button" data-action="add">+ Thêm phòng</button></div><div class="item-list">'+rooms.map(roomHtml).join("")+'</div></section></main>';DashboardSetupBridge.resize()}
  function roomHtml(room,index){var f=room.fields||{},cmd=room.commands||{};return'<article class="item-card" data-room="'+index+'"><div class="item-top"><div><span class="badge">#'+(index+1)+'</span> <strong>'+esc(room.code)+'</strong></div><div><button class="secondary" type="button" data-action="clone" data-index="'+index+'">Nhân bản</button> <button class="danger" type="button" data-action="delete" data-index="'+index+'">Xóa</button></div></div><div class="grid">'+roomInput("Mã phòng","code",room.code)+roomInput("Người thuê","tenant",room.tenant)+roomInput("Device key","sessionId",room.sessionId)+roomInput("Tiền phòng (₫)","rent",room.rent,"number")+roomInput("Chỉ số điện đầu tháng","electricStart",room.electricStart,"number")+roomInput("Chỉ số nước đầu tháng","waterStart",room.waterStart,"number")+'</div><div class="advanced"><h3>Field và lệnh thiết bị</h3><div class="grid">'+fieldInput("Field điện kWh","electricity",f.electricity)+fieldInput("Field nước m³","water",f.water)+fieldInput("Field công suất W","power",f.power)+fieldInput("Field thanh toán ON/OFF","paid",f.paid)+fieldInput("Field relay điện","relay",f.relay)+commandInput("Lệnh bật điện","on",cmd.on)+commandInput("Lệnh tắt điện","off",cmd.off)+'</div></div></article>'}
  function roomInput(label,key,value,type){return'<label>'+esc(label)+'<input data-room-key="'+key+'" type="'+(type||"text")+'" value="'+esc(value)+'"></label>'}function fieldInput(label,key,value){return'<label>'+esc(label)+'<input data-field-key="'+key+'" value="'+esc(value)+'"></label>'}function commandInput(label,key,value){return'<label>'+esc(label)+'<input data-command-key="'+key+'" value="'+esc(value)+'"></label>'}
  function read(){var c=state.config;document.querySelectorAll("[data-key]").forEach(function(n){var k=n.getAttribute("data-key");c[k]=["electricRate","waterRate","serviceFee","dueDay"].indexOf(k)>=0?num(n.value,c[k]):safe(n.value,c[k])});document.querySelectorAll("[data-room]").forEach(function(card){var room=c.rooms[Number(card.getAttribute("data-room"))];card.querySelectorAll("[data-room-key]").forEach(function(n){var k=n.getAttribute("data-room-key");room[k]=["rent","electricStart","waterStart"].indexOf(k)>=0?num(n.value,room[k]):safe(n.value,room[k])});room.fields=room.fields||{};card.querySelectorAll("[data-field-key]").forEach(function(n){room.fields[n.getAttribute("data-field-key")]=safe(n.value,"")});room.commands=room.commands||{};card.querySelectorAll("[data-command-key]").forEach(function(n){room.commands[n.getAttribute("data-command-key")]=safe(n.value,"")})})}
  function initialize(payload){state.context=clone(payload&&payload.context||{});var incoming=payload&&payload.config;state.config=clone(incoming&&Object.keys(incoming).length?incoming:DEFAULT);if(!state.config.syncId)state.config.syncId=state.context.syncId||"";(state.config.rooms||[]).forEach(function(r){if(!r.sessionId)r.sessionId=state.context.sessionId||""});render()}
  function collect(){read();if(!state.config.title)throw new Error("Hãy nhập tên dashboard.");if(!state.config.rooms.length)throw new Error("Cần ít nhất một phòng.");state.config.dueDay=Math.max(1,Math.min(28,Math.round(num(state.config.dueDay,5))));return clone(state.config)}
  document.addEventListener("click",function(event){var button=event.target.closest("[data-action]");if(!button)return;read();var action=button.getAttribute("data-action"),index=Number(button.getAttribute("data-index"));if(action==="add")state.config.rooms.push(roomFactory(state.config.rooms.length,"P"+(state.config.rooms.length+1)));else if(action==="clone"){var copy=clone(state.config.rooms[index]);copy.code=safe(copy.code,"Phòng")+" copy";state.config.rooms.splice(index+1,0,copy)}else if(action==="delete"){if(state.config.rooms.length<=1){DashboardSetupBridge.error("Cần giữ ít nhất một phòng.");return}state.config.rooms.splice(index,1)}render()});
  render();DashboardSetupBridge.start({onInit:initialize,onCollect:collect});
})();
