(function(){
  "use strict";
  var state={config:null,values:Object.create(null),rows:[],connection:"connecting",lastSeen:0,stream:null,reconnect:0};
  function id(v){return document.getElementById(v)}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function text(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}
  function num(v){if(v===null||v===undefined||v==="")return null;var n=Number(v);return Number.isFinite(n)?n:null}
  function on(v){return /^(1|true|on|open|running|active)$/i.test(String(v==null?"":v).trim())}
  function hydrate(raw){var c=window.ROSA_SIMULATOR_CONTEXT||{};return String(raw||"").replace(/<<sessionid>>/gi,text(c.sessionId,"IO123abcd@simulate")).replace(/<<syncid>>/gi,text(c.syncId,"SIM_SYNC"))}
  function parse(){try{return JSON.parse(hydrate(id("smart-greenhouse-config").textContent))}catch(e){return null}}
  function key(field){return String(field||"").toLowerCase()}
  function read(field){return state.values[key(field)]}
  function setValues(payload){if(!payload||typeof payload!=="object")return;Object.keys(payload).forEach(function(field){state.values[key(field)]=payload[field]})}
  function allFields(){var f=state.config.fields||{},out=Object.keys(f).map(function(k){return f[k]}).filter(Boolean);(state.config.zones||[]).forEach(function(z){if(z.soilField)out.push(z.soilField);if(z.valveField)out.push(z.valveField)});return out.filter(function(v,i,a){return a.indexOf(v)===i})}
  function telemetryUrl(){var c=state.config;if(!c.sessionId||!c.syncId)return"";var q=new URLSearchParams();q.set("fields",allFields().join(","));return"/api/"+encodeURIComponent(c.sessionId)+"/"+encodeURIComponent(c.syncId)+"/iotelemetry?"+q}
  function historyUrl(){var c=state.config;if(!c.sessionId||!c.syncId)return"";var q=new URLSearchParams(),now=Date.now();q.set("fields",[c.fields.temperature,c.fields.humidity].filter(Boolean).join(","));q.set("from",String(now-c.historyMinutes*60000));q.set("to",String(now));return"/api/"+encodeURIComponent(c.sessionId)+"/"+encodeURIComponent(c.syncId)+"/iotimeseries?"+q}
  function streamUrl(){var c=state.config;if(!c.sessionId)return"";var q=new URLSearchParams();q.set("fields",allFields().join(","));return"/api/"+encodeURIComponent(c.sessionId)+"/stream?"+q}
  function commandUrl(){var s=String(state.config.sessionId||""),p=s.indexOf("@");return p>0?"https://iot.ioeasy.com/cmd/"+encodeURIComponent(s.slice(0,p))+"?apiKey="+encodeURIComponent(s.slice(p+1)):""}
  function hasData(){return Object.keys(state.values).length>0}
  function averageSoil(){var vals=(state.config.zones||[]).map(function(z){return num(read(z.soilField))}).filter(function(v){return v!==null});return vals.length?vals.reduce(function(s,v){return s+v},0)/vals.length:null}
  function issues(){var c=state.config,t=c.thresholds||{},f=c.fields||{},list=[],temperature=num(read(f.temperature)),humidity=num(read(f.humidity)),co2=num(read(f.co2)),water=num(read(f.waterLevel));if(state.connection==="offline")list.push("Mất kết nối thiết bị");if(temperature!==null&&(temperature<t.temperatureMin||temperature>t.temperatureMax))list.push("Nhiệt độ ngoài ngưỡng");if(humidity!==null&&(humidity<t.humidityMin||humidity>t.humidityMax))list.push("Độ ẩm không khí ngoài ngưỡng");if(co2!==null&&co2>t.co2Max)list.push("CO₂ vượt ngưỡng");if(water!==null&&water<t.waterLow)list.push("Mực nước bồn thấp");(c.zones||[]).forEach(function(z){var soil=num(read(z.soilField));if(soil!==null&&soil<t.soilMin)list.push(z.name+" thiếu ẩm")});if(read(f.alarm)!=null&&on(read(f.alarm)))list.push("Thiết bị báo lỗi");return list}
  function value(v,digits,unit){return v===null?"--":v.toLocaleString("vi-VN",{minimumFractionDigits:digits,maximumFractionDigits:digits})+(unit||"")}
  function renderKpis(){var c=state.config,t=c.thresholds,f=c.fields,temp=num(read(f.temperature)),humidity=num(read(f.humidity)),water=num(read(f.waterLevel)),soil=averageSoil();id("gh-kpis").innerHTML=[
    ["Nhiệt độ không khí",value(temp,1,"°C"),"Mục tiêu "+t.temperatureMin+"–"+t.temperatureMax+"°C",temp!==null&&(temp<t.temperatureMin||temp>t.temperatureMax)],
    ["Độ ẩm không khí",value(humidity,0,"%"),"Mục tiêu "+t.humidityMin+"–"+t.humidityMax+"%",humidity!==null&&(humidity<t.humidityMin||humidity>t.humidityMax)],
    ["Mực nước bồn",value(water,0,"%"),water===null?"Chưa có dữ liệu":water<t.waterLow?"Cần bổ sung nước":"Đủ cho hệ thống",water!==null&&water<t.waterLow],
    ["Độ ẩm đất TB",value(soil,0,"%"),"Ngưỡng tưới "+t.soilMin+"%",soil!==null&&soil<t.soilMin]
  ].map(function(k){return'<article class="gh-kpi"><span>'+k[0]+'</span><strong data-state="'+(k[3]?'danger':'normal')+'">'+k[1]+'</strong><small>'+k[2]+'</small></article>'}).join("")}
  function renderClimate(){var f=state.config.fields,t=state.config.thresholds,co2=num(read(f.co2));id("gh-climate").innerHTML=[
    ["Ánh sáng",value(num(read(f.light)),0," lux"),false],
    ["Nồng độ CO₂",value(co2,0," ppm"),co2!==null&&co2>t.co2Max],
    ["Dinh dưỡng EC",value(num(read(f.ec)),2," mS/cm"),false],
    ["Độ pH",value(num(read(f.ph)),1,""),false]
  ].map(function(k){return'<div class="gh-metric"><span>'+k[0]+'</span><strong data-state="'+(k[2]?'danger':'normal')+'">'+k[1]+'</strong></div>'}).join("")}
  function deviceHtml(label,stateField,onAction,offAction){var raw=read(stateField),active=on(raw);return'<div class="gh-device"><div class="gh-device-info"><span>'+esc(label)+'</span><strong>'+(raw==null?'Chưa có dữ liệu':active?'Đang bật':'Đang tắt')+'</strong></div><button type="button" class="gh-switch" data-device-action="'+(active?offAction:onAction)+'" data-state="'+(active?'on':'off')+'" aria-label="Điều khiển '+esc(label)+'"></button></div>'}
  function renderDevices(){var f=state.config.fields;id("gh-devices").innerHTML=deviceHtml("Bơm tưới",f.pump,"pumpOn","pumpOff")+deviceHtml("Quạt thông gió",f.fan,"fanOn","fanOff")+deviceHtml("Phun sương",f.mist,"mistOn","mistOff")+deviceHtml("Mái che",f.roof,"roofOn","roofOff")+deviceHtml("Đèn trồng cây",f.growLight,"growLightOn","growLightOff")}
  function zoneHtml(z,index){var soil=num(read(z.soilField)),valveRaw=read(z.valveField),valve=on(valveRaw),low=soil!==null&&soil<state.config.thresholds.soilMin,pct=soil===null?0:Math.max(0,Math.min(100,soil));return'<article class="gh-zone" style="--accent:'+esc(z.accent||"#22c55e")+'"><div class="gh-zone-head"><div><h3>'+esc(z.name)+'</h3><p>'+esc(z.crop||"")+'</p></div><span class="gh-zone-state" data-state="'+(low?'danger':'normal')+'">'+(soil===null?'CHỜ DỮ LIỆU':low?'CẦN TƯỚI':'ĐỦ ẨM')+'</span></div><div class="gh-soil-row"><strong class="gh-soil-value">'+value(soil,0,"%")+'</strong><div><div class="gh-progress"><i style="width:'+pct+'%"></i></div><span class="gh-small">Ngưỡng '+state.config.thresholds.soilMin+'%</span></div></div><div class="gh-zone-foot"><span>Van tưới: '+(valveRaw==null?'--':valve?'Đang mở':'Đã đóng')+'</span><button type="button" class="gh-switch" data-zone-index="'+index+'" data-zone-state="'+(valve?'on':'off')+'" data-state="'+(valve?'on':'off')+'" aria-label="Điều khiển van '+esc(z.name)+'"></button></div></article>'}
  function renderZones(){var zones=state.config.zones||[],low=zones.filter(function(z){var v=num(read(z.soilField));return v!==null&&v<state.config.thresholds.soilMin}).length;id("gh-zones").innerHTML=zones.length?zones.map(zoneHtml).join(""):'<div class="gh-panel">Chưa có khu vực trồng nào được cấu hình.</div>';id("gh-zone-summary").textContent=hasData()?(low?low+" khu vực cần tưới":"Tất cả khu vực đủ ẩm"):"Đang chờ dữ liệu"}
  function chartPath(points,field){var rows=points.filter(function(r){return key(r.field)===key(field)&&Number.isFinite(Number(r.ts))&&Number.isFinite(Number(r.value))}).slice(-180);if(!rows.length)return"";var vals=rows.map(function(r){return Number(r.value)}),min=Math.min.apply(null,vals),max=Math.max.apply(null,vals);if(max-min<1){min-=.5;max+=.5}return rows.map(function(r,i){var x=18+i*(604/Math.max(1,rows.length-1)),y=150-(Number(r.value)-min)/(max-min)*112;return(i?"L":"M")+x.toFixed(1)+" "+y.toFixed(1)}).join(" ")}
  function renderChart(){id("gh-chart-temp").setAttribute("d",chartPath(state.rows,state.config.fields.temperature));id("gh-chart-humidity").setAttribute("d",chartPath(state.rows,state.config.fields.humidity))}
  function renderStatus(){var list=issues(),alert=id("gh-alert"),live=id("gh-live-dot"),label=id("gh-live-text");alert.hidden=!list.length;alert.textContent=list.length?"⚠ "+list.join("  •  "):"";live.setAttribute("data-state",state.connection);label.textContent=state.connection==="online"?"Đang trực tuyến":state.connection==="offline"?"Mất kết nối":"Đang kết nối"}
  function render(){if(!state.config)return;renderKpis();renderClimate();renderDevices();renderZones();renderChart();renderStatus()}
  function applyRows(rows){var wanted=[key(state.config.fields.temperature),key(state.config.fields.humidity)];(rows||[]).forEach(function(r){if(wanted.indexOf(key(r.field))<0)return;var row={field:r.field,ts:Number(r.ts),value:Number(r.value)};if(Number.isFinite(row.ts)&&Number.isFinite(row.value))state.rows.push(row)});var cutoff=Date.now()-state.config.historyMinutes*60000;state.rows=state.rows.filter(function(r){return r.ts>=cutoff}).slice(-360);renderChart()}
  function fetchJson(url){if(!url)return Promise.resolve(null);return fetch(url,{cache:"no-store"}).then(function(r){return r.ok?r.json():null}).catch(function(){return null})}
  function bootstrap(){return Promise.all([fetchJson(telemetryUrl()),fetchJson(historyUrl())]).then(function(parts){var tele=parts[0]&&parts[0].c2,hist=parts[1]&&parts[1].c2;setValues(tele&&tele.payload||{});state.lastSeen=Number(tele&&tele.serverTime)||0;state.rows=[];applyRows(hist&&hist.rows||[]);render()})}
  function connect(){var url=streamUrl();if(!url||typeof EventSource==="undefined"){state.connection="offline";renderStatus();return}try{var source=new EventSource(url);state.stream=source;source.onopen=function(){state.connection="online";renderStatus()};source.onmessage=function(e){try{var d=JSON.parse(e.data);state.connection="online";if(d.type==="telemetry"&&d.payload){setValues(d.payload);state.lastSeen=Number(d.serverTime)||Date.now();render()}else if(d.type==="timeseries")applyRows(d.rows)}catch(x){}};source.onerror=function(){source.close();state.stream=null;state.connection="offline";renderStatus();clearTimeout(state.reconnect);state.reconnect=setTimeout(connect,3000)}}catch(e){state.connection="offline";renderStatus()}}
  function toast(message,type){var n=document.createElement("div");n.className="gh-toast "+(type||"");n.textContent=message;id("gh-toast-stack").appendChild(n);setTimeout(function(){n.remove()},3000)}
  function send(command){var url=commandUrl();if(!command||!url)return Promise.reject(new Error("missing"));var resolver=window.AIBridgeCommandTemplate,p=resolver&&resolver.resolveCommandTemplate?resolver.resolveCommandTemplate(command):Promise.resolve(command);return p.then(function(value){return fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cmd:value})}).then(function(r){if(!r.ok)throw new Error("failed")})})}
  function bind(){document.addEventListener("click",function(e){var button=e.target.closest("[data-device-action],[data-zone-index]");if(!button)return;var command="",label="thiết bị";if(button.hasAttribute("data-device-action")){command=state.config.commands[button.getAttribute("data-device-action")]}else{var zone=state.config.zones[Number(button.getAttribute("data-zone-index"))];if(!zone)return;command=button.getAttribute("data-zone-state")==="on"?zone.valveOff:zone.valveOn;label=zone.name}button.disabled=true;send(command).then(function(){toast("Đã gửi lệnh đến "+label+". Đang chờ telemetry xác nhận.")}).catch(function(){toast("Không gửi được lệnh điều khiển.","error")}).finally(function(){button.disabled=false})})}
  function theme(){var p=id("theme-picker"),t=id("theme-picker-toggle"),m=id("theme-picker-menu");function open(v){p.classList.toggle("is-open",v);t.setAttribute("aria-expanded",v?"true":"false")}t.onclick=function(e){e.stopPropagation();open(!p.classList.contains("is-open"))};m.onclick=function(e){var b=e.target.closest("[data-theme-option]");if(!b)return;var v=b.getAttribute("data-theme-option");document.documentElement.setAttribute("data-theme",v);try{localStorage.setItem("sample-dashboard-theme",v)}catch(x){}m.querySelectorAll("button").forEach(function(n){n.classList.toggle("is-active",n===b)});open(false)};document.addEventListener("click",function(e){if(!p.contains(e.target))open(false)})}
  function init(){var c=parse();if(!c){id("gh-zone-summary").textContent="Cấu hình template không hợp lệ.";return}state.config=c;state.config.historyMinutes=Number(c.historyMinutes)||1440;id("gh-title").textContent=text(c.title,"Nhà kính thông minh");id("gh-subtitle").textContent=text(c.subtitle,"");id("gh-history-range").value=String(state.config.historyMinutes);id("gh-history-range").onchange=function(){state.config.historyMinutes=Number(this.value)||1440;state.rows=[];fetchJson(historyUrl()).then(function(p){applyRows(p&&p.c2&&p.c2.rows||[])})};function clock(){id("gh-clock").textContent=new Date().toLocaleTimeString("vi-VN")}clock();setInterval(clock,1000);bind();theme();render();bootstrap().finally(connect)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
