(function(){
  "use strict";
  function zone(name,crop,suffix,accent,index){return{name:name,crop:crop,accent:accent,soilField:"gh_soil_"+suffix,valveField:"gh_valve_"+suffix,valveOn:"D1O"+(index+6),valveOff:"D2O"+(index+6)}}
  var DEFAULT={locale:"vi",title:"Nhà kính thông minh",subtitle:"Vi khí hậu, tưới tiêu và thiết bị trong một màn hình",sessionId:"<<sessionid>>",syncId:"<<syncid>>",historyMinutes:1440,thresholds:{temperatureMin:18,temperatureMax:32,humidityMin:45,humidityMax:85,soilMin:35,co2Max:1000,waterLow:25},fields:{temperature:"gh_air_temperature",humidity:"gh_air_humidity",light:"gh_light_lux",co2:"gh_co2_ppm",waterLevel:"gh_water_level_pct",ec:"gh_ec_ms",ph:"gh_ph",pump:"gh_pump",fan:"gh_fan",mist:"gh_mist",roof:"gh_roof",growLight:"gh_grow_light",alarm:"gh_alarm"},commands:{pumpOn:"D1O1",pumpOff:"D2O1",fanOn:"D1O2",fanOff:"D2O2",mistOn:"D1O3",mistOff:"D2O3",roofOn:"D1O4",roofOff:"D2O4",growLightOn:"D1O5",growLightOff:"D2O5"},zones:[zone("Luống cà chua","Cà chua bi","a","#22c55e",0),zone("Luống rau lá","Xà lách thủy canh","b","#14b8a6",1),zone("Luống dưa lưới","Dưa lưới","c","#f59e0b",2)]};
  var state={config:clone(DEFAULT),context:{}};
  function clone(v){return JSON.parse(JSON.stringify(v==null?{}:v))}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function safe(v,f){v=String(v==null?"":v).trim();return v||String(f||"")}
  function num(v,f){var n=Number(v);return Number.isFinite(n)?n:Number(f||0)}
  function input(label,attr,key,value,type){return'<label>'+esc(label)+'<input '+attr+'="'+key+'" type="'+(type||"text")+'" value="'+esc(value)+'"></label>'}
  function zoneHtml(z,index){return'<article class="item-card" data-zone="'+index+'"><div class="item-top"><div><h3>'+esc(z.name||("Khu "+(index+1)))+'</h3><div class="status">Cảm biến đất và van tưới riêng</div></div><div><button class="secondary" data-action="clone" data-index="'+index+'">Nhân bản</button> <button class="danger" data-action="delete" data-index="'+index+'">Xóa</button></div></div><div class="grid">'+input("Tên khu","data-zone-key","name",z.name)+input("Cây trồng","data-zone-key","crop",z.crop)+input("Màu nhận diện","data-zone-key","accent",z.accent,"color")+input("Field độ ẩm đất","data-zone-key","soilField",z.soilField)+input("Field trạng thái van","data-zone-key","valveField",z.valveField)+input("Lệnh mở van","data-zone-key","valveOn",z.valveOn)+input("Lệnh đóng van","data-zone-key","valveOff",z.valveOff)+'</div></article>'}
  function render(){var c=state.config,zones=Array.isArray(c.zones)?c.zones:[],fieldLabels={temperature:"Nhiệt độ không khí",humidity:"Độ ẩm không khí",light:"Ánh sáng",co2:"Nồng độ CO₂",waterLevel:"Mực nước bồn",ec:"Chỉ số EC",ph:"Độ pH",pump:"Bơm tưới",fan:"Quạt thông gió",mist:"Phun sương",roof:"Mái che",growLight:"Đèn trồng cây",alarm:"Cảnh báo thiết bị"},commandLabels={pumpOn:"Bật bơm",pumpOff:"Tắt bơm",fanOn:"Bật quạt",fanOff:"Tắt quạt",mistOn:"Bật phun sương",mistOff:"Tắt phun sương",roofOn:"Mở mái che",roofOff:"Đóng mái che",growLightOn:"Bật đèn",growLightOff:"Tắt đèn"};document.body.innerHTML='<main class="shell"><header class="head"><div><h1>Cài đặt nhà kính thông minh</h1><div class="status">Cấu hình cảm biến, ngưỡng, thiết bị và từng khu vực trồng.</div></div><div class="badge">'+zones.length+' khu vực</div></header><section class="panel"><h2>Thông tin chung</h2><div class="grid">'+input("Tên dashboard","data-general","title",c.title)+input("Device key","data-general","sessionId",c.sessionId)+input("AccountID","data-general","syncId",c.syncId)+input("Lịch sử mặc định (phút)","data-general","historyMinutes",c.historyMinutes,"number")+'<label class="full">Mô tả<input data-general="subtitle" value="'+esc(c.subtitle)+'"></label></div></section><section class="panel"><h2>Ngưỡng vận hành</h2><div class="grid">'+input("Nhiệt độ thấp (°C)","data-threshold","temperatureMin",c.thresholds.temperatureMin,"number")+input("Nhiệt độ cao (°C)","data-threshold","temperatureMax",c.thresholds.temperatureMax,"number")+input("Độ ẩm thấp (%)","data-threshold","humidityMin",c.thresholds.humidityMin,"number")+input("Độ ẩm cao (%)","data-threshold","humidityMax",c.thresholds.humidityMax,"number")+input("Độ ẩm đất cần tưới (%)","data-threshold","soilMin",c.thresholds.soilMin,"number")+input("CO₂ cao (ppm)","data-threshold","co2Max",c.thresholds.co2Max,"number")+input("Mực nước thấp (%)","data-threshold","waterLow",c.thresholds.waterLow,"number")+'</div></section><section class="panel"><h2>Field cảm biến và thiết bị</h2><div class="grid">'+Object.keys(c.fields||{}).map(function(k){return input(fieldLabels[k]||k,"data-field",k,c.fields[k])}).join("")+'</div><div class="advanced"><h3>Lệnh điều khiển</h3><div class="grid">'+Object.keys(c.commands||{}).map(function(k){return input(commandLabels[k]||k,"data-command",k,c.commands[k])}).join("")+'</div></div></section><section class="panel"><div class="toolbar"><h2>Khu vực trồng</h2><button data-action="add">+ Thêm khu vực</button></div><div class="item-list">'+zones.map(zoneHtml).join("")+'</div></section></main>';DashboardSetupBridge.resize()}
  function read(){var c=state.config;document.querySelectorAll("[data-general]").forEach(function(n){var k=n.getAttribute("data-general");c[k]=k==="historyMinutes"?Math.max(15,num(n.value,1440)):safe(n.value,c[k])});c.thresholds=c.thresholds||{};document.querySelectorAll("[data-threshold]").forEach(function(n){c.thresholds[n.getAttribute("data-threshold")]=num(n.value,c.thresholds[n.getAttribute("data-threshold")])});c.fields=c.fields||{};document.querySelectorAll("[data-field]").forEach(function(n){c.fields[n.getAttribute("data-field")]=safe(n.value,"")});c.commands=c.commands||{};document.querySelectorAll("[data-command]").forEach(function(n){c.commands[n.getAttribute("data-command")]=safe(n.value,"")});document.querySelectorAll("[data-zone]").forEach(function(card){var z=c.zones[Number(card.getAttribute("data-zone"))];card.querySelectorAll("[data-zone-key]").forEach(function(n){z[n.getAttribute("data-zone-key")]=safe(n.value,z[n.getAttribute("data-zone-key")])})})}
  function initialize(payload){state.context=clone(payload&&payload.context||{});var incoming=payload&&payload.config;state.config=clone(incoming&&Object.keys(incoming).length?incoming:DEFAULT);if(!state.config.sessionId)state.config.sessionId=state.context.sessionId||"";if(!state.config.syncId)state.config.syncId=state.context.syncId||"";render()}
  function collect(){read();var c=state.config,t=c.thresholds;if(!c.title)throw new Error("Hãy nhập tên dashboard.");if(!c.zones||!c.zones.length)throw new Error("Cần ít nhất một khu vực trồng.");if(t.temperatureMin>=t.temperatureMax)throw new Error("Ngưỡng nhiệt độ thấp phải nhỏ hơn ngưỡng cao.");if(t.humidityMin>=t.humidityMax)throw new Error("Ngưỡng độ ẩm thấp phải nhỏ hơn ngưỡng cao.");c.zones.forEach(function(z){if(!z.name||!z.soilField)throw new Error("Mỗi khu vực cần có tên và field độ ẩm đất.")});return clone(c)}
  document.addEventListener("click",function(e){var b=e.target.closest("[data-action]");if(!b)return;e.preventDefault();read();var action=b.getAttribute("data-action"),index=Number(b.getAttribute("data-index"));if(action==="add"){var n=state.config.zones.length,suffix=String.fromCharCode(97+n);state.config.zones.push(zone("Khu vực "+(n+1),"Cây trồng",suffix,"#8b5cf6",n))}else if(action==="clone"){var copy=clone(state.config.zones[index]);copy.name=safe(copy.name,"Khu vực")+" copy";state.config.zones.splice(index+1,0,copy)}else if(action==="delete"){if(state.config.zones.length<=1){DashboardSetupBridge.error("Cần giữ ít nhất một khu vực.");return}state.config.zones.splice(index,1)}render()});
  render();DashboardSetupBridge.start({onInit:initialize,onCollect:collect});
})();
